--
-- PostgreSQL database dump
--

\restrict U1H5thgiqNALB7cyghGbtyPUFdV9jGJmNxvXs2CvVERUO4jTyhsCEBa0LUCZrCU

-- Dumped from database version 14.18 (Debian 14.18-1.pgdg120+1)
-- Dumped by pg_dump version 16.10 (Ubuntu 16.10-0ubuntu0.24.04.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: baruser
--

-- *not* creating schema, since initdb creates it


ALTER SCHEMA public OWNER TO baruser;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: baruser
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO baruser;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: baruser
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: baruser
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO baruser;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: baruser
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: baruser
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO baruser;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: baruser
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user; Type: TABLE; Schema: public; Owner: baruser
--

CREATE TABLE public.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


ALTER TABLE public.auth_user OWNER TO baruser;

--
-- Name: auth_user_groups; Type: TABLE; Schema: public; Owner: baruser
--

CREATE TABLE public.auth_user_groups (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.auth_user_groups OWNER TO baruser;

--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: baruser
--

ALTER TABLE public.auth_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: public; Owner: baruser
--

ALTER TABLE public.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_user_permissions; Type: TABLE; Schema: public; Owner: baruser
--

CREATE TABLE public.auth_user_user_permissions (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_user_user_permissions OWNER TO baruser;

--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: baruser
--

ALTER TABLE public.auth_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: barbackend_cart; Type: TABLE; Schema: public; Owner: baruser
--

CREATE TABLE public.barbackend_cart (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    user_id bigint NOT NULL,
    note text NOT NULL,
    updated_at timestamp with time zone NOT NULL
);


ALTER TABLE public.barbackend_cart OWNER TO baruser;

--
-- Name: barbackend_cart_id_seq; Type: SEQUENCE; Schema: public; Owner: baruser
--

ALTER TABLE public.barbackend_cart ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.barbackend_cart_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: barbackend_cartitem; Type: TABLE; Schema: public; Owner: baruser
--

CREATE TABLE public.barbackend_cartitem (
    id bigint NOT NULL,
    quantity integer NOT NULL,
    added_at timestamp with time zone NOT NULL,
    cart_id bigint NOT NULL,
    drink_id bigint NOT NULL,
    CONSTRAINT barbackend_cartitem_quantity_check CHECK ((quantity >= 0))
);


ALTER TABLE public.barbackend_cartitem OWNER TO baruser;

--
-- Name: barbackend_cartitem_id_seq; Type: SEQUENCE; Schema: public; Owner: baruser
--

ALTER TABLE public.barbackend_cartitem ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.barbackend_cartitem_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: barbackend_drink; Type: TABLE; Schema: public; Owner: baruser
--

CREATE TABLE public.barbackend_drink (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    description text NOT NULL,
    price numeric(6,2) NOT NULL,
    available boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    image character varying(100) NOT NULL,
    stock integer NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    category character varying(50) NOT NULL,
    unavailable_threshold integer NOT NULL,
    low_stock_threshold integer NOT NULL,
    CONSTRAINT barbackend_drink_low_stock_threshold_check CHECK ((unavailable_threshold >= 0)),
    CONSTRAINT barbackend_drink_low_stock_threshold_check1 CHECK ((low_stock_threshold >= 0)),
    CONSTRAINT barbackend_drink_stock_check CHECK ((stock >= 0))
);


ALTER TABLE public.barbackend_drink OWNER TO baruser;

--
-- Name: barbackend_drink_id_seq; Type: SEQUENCE; Schema: public; Owner: baruser
--

ALTER TABLE public.barbackend_drink ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.barbackend_drink_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: barbackend_order; Type: TABLE; Schema: public; Owner: baruser
--

CREATE TABLE public.barbackend_order (
    id bigint NOT NULL,
    status character varying(30) NOT NULL,
    total_price numeric(8,2) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    user_id bigint NOT NULL,
    note text NOT NULL
);


ALTER TABLE public.barbackend_order OWNER TO baruser;

--
-- Name: barbackend_order_id_seq; Type: SEQUENCE; Schema: public; Owner: baruser
--

ALTER TABLE public.barbackend_order ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.barbackend_order_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: barbackend_orderitem; Type: TABLE; Schema: public; Owner: baruser
--

CREATE TABLE public.barbackend_orderitem (
    id bigint NOT NULL,
    quantity integer NOT NULL,
    drink_id bigint NOT NULL,
    order_id bigint NOT NULL,
    CONSTRAINT barbackend_orderitem_quantity_check CHECK ((quantity >= 0))
);


ALTER TABLE public.barbackend_orderitem OWNER TO baruser;

--
-- Name: barbackend_orderitem_id_seq; Type: SEQUENCE; Schema: public; Owner: baruser
--

ALTER TABLE public.barbackend_orderitem ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.barbackend_orderitem_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: barbackend_orderotp; Type: TABLE; Schema: public; Owner: baruser
--

CREATE TABLE public.barbackend_orderotp (
    id bigint NOT NULL,
    code_hash character varying(128) NOT NULL,
    code_plain character varying(10) NOT NULL,
    last_sent_at timestamp with time zone,
    is_used boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    order_id bigint NOT NULL
);


ALTER TABLE public.barbackend_orderotp OWNER TO baruser;

--
-- Name: barbackend_orderotp_id_seq; Type: SEQUENCE; Schema: public; Owner: baruser
--

ALTER TABLE public.barbackend_orderotp ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.barbackend_orderotp_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: barbackend_user; Type: TABLE; Schema: public; Owner: baruser
--

CREATE TABLE public.barbackend_user (
    id bigint NOT NULL,
    username character varying(50) NOT NULL,
    email character varying(254) NOT NULL,
    role character varying(20) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    is_active boolean NOT NULL,
    is_staff boolean NOT NULL,
    is_superuser boolean NOT NULL,
    last_login timestamp with time zone,
    password character varying(128) NOT NULL,
    is_admin boolean NOT NULL
);


ALTER TABLE public.barbackend_user OWNER TO baruser;

--
-- Name: barbackend_user_groups; Type: TABLE; Schema: public; Owner: baruser
--

CREATE TABLE public.barbackend_user_groups (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.barbackend_user_groups OWNER TO baruser;

--
-- Name: barbackend_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: baruser
--

ALTER TABLE public.barbackend_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.barbackend_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: barbackend_user_id_seq; Type: SEQUENCE; Schema: public; Owner: baruser
--

ALTER TABLE public.barbackend_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.barbackend_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: barbackend_user_user_permissions; Type: TABLE; Schema: public; Owner: baruser
--

CREATE TABLE public.barbackend_user_user_permissions (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.barbackend_user_user_permissions OWNER TO baruser;

--
-- Name: barbackend_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: baruser
--

ALTER TABLE public.barbackend_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.barbackend_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: baruser
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO baruser;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: baruser
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: baruser
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO baruser;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: baruser
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: baruser
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO baruser;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: baruser
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: baruser
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO baruser;

--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: baruser
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: baruser
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: baruser
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	2	add_permission
6	Can change permission	2	change_permission
7	Can delete permission	2	delete_permission
8	Can view permission	2	view_permission
9	Can add group	3	add_group
10	Can change group	3	change_group
11	Can delete group	3	delete_group
12	Can view group	3	view_group
13	Can add user	4	add_user
14	Can change user	4	change_user
15	Can delete user	4	delete_user
16	Can view user	4	view_user
17	Can add content type	5	add_contenttype
18	Can change content type	5	change_contenttype
19	Can delete content type	5	delete_contenttype
20	Can view content type	5	view_contenttype
21	Can add session	6	add_session
22	Can change session	6	change_session
23	Can delete session	6	delete_session
24	Can view session	6	view_session
25	Can add drink	7	add_drink
26	Can change drink	7	change_drink
27	Can delete drink	7	delete_drink
28	Can view drink	7	view_drink
29	Can add order	8	add_order
30	Can change order	8	change_order
31	Can delete order	8	delete_order
32	Can view order	8	view_order
33	Can add user	9	add_user
34	Can change user	9	change_user
35	Can delete user	9	delete_user
36	Can view user	9	view_user
37	Can add order item	10	add_orderitem
38	Can change order item	10	change_orderitem
39	Can delete order item	10	delete_orderitem
40	Can view order item	10	view_orderitem
41	Can add cart	11	add_cart
42	Can change cart	11	change_cart
43	Can delete cart	11	delete_cart
44	Can view cart	11	view_cart
45	Can add cart item	12	add_cartitem
46	Can change cart item	12	change_cartitem
47	Can delete cart item	12	delete_cartitem
48	Can view cart item	12	view_cartitem
49	Can add order otp	13	add_orderotp
50	Can change order otp	13	change_orderotp
51	Can delete order otp	13	delete_orderotp
52	Can view order otp	13	view_orderotp
\.


--
-- Data for Name: auth_user; Type: TABLE DATA; Schema: public; Owner: baruser
--

COPY public.auth_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined) FROM stdin;
\.


--
-- Data for Name: auth_user_groups; Type: TABLE DATA; Schema: public; Owner: baruser
--

COPY public.auth_user_groups (id, user_id, group_id) FROM stdin;
\.


--
-- Data for Name: auth_user_user_permissions; Type: TABLE DATA; Schema: public; Owner: baruser
--

COPY public.auth_user_user_permissions (id, user_id, permission_id) FROM stdin;
\.


--
-- Data for Name: barbackend_cart; Type: TABLE DATA; Schema: public; Owner: baruser
--

COPY public.barbackend_cart (id, created_at, user_id, note, updated_at) FROM stdin;
18	2025-09-24 12:30:25.938759+00	14	Cart for default_staff	2025-09-24 12:30:25.938765+00
19	2025-09-24 12:30:25.940206+00	15	Cart for alice	2025-09-24 12:30:25.940211+00
20	2025-09-24 12:30:25.941477+00	16	Cart for bob	2025-09-24 12:30:25.941481+00
21	2025-09-24 12:30:25.943048+00	17	Cart for carol	2025-09-24 12:30:25.943053+00
22	2025-09-24 12:30:25.944267+00	18	Cart for admin	2025-09-24 12:30:25.944272+00
23	2025-09-24 12:30:25.945349+00	19	Cart for dave	2025-09-24 12:30:25.945354+00
24	2025-09-24 12:30:25.946454+00	20	Cart for eve	2025-09-24 12:30:25.94646+00
\.


--
-- Data for Name: barbackend_cartitem; Type: TABLE DATA; Schema: public; Owner: baruser
--

COPY public.barbackend_cartitem (id, quantity, added_at, cart_id, drink_id) FROM stdin;
53	1	2025-09-24 12:30:25.939261+00	18	41
54	1	2025-09-24 12:30:25.939623+00	18	38
55	1	2025-09-24 12:30:25.939916+00	18	46
56	3	2025-09-24 12:30:25.940518+00	19	41
57	2	2025-09-24 12:30:25.940811+00	19	55
58	1	2025-09-24 12:30:25.941149+00	19	40
59	1	2025-09-24 12:30:25.941893+00	20	38
60	3	2025-09-24 12:30:25.942294+00	20	40
61	3	2025-09-24 12:30:25.942676+00	20	44
62	3	2025-09-24 12:30:25.943406+00	21	38
63	3	2025-09-24 12:30:25.94371+00	21	55
64	3	2025-09-24 12:30:25.943992+00	21	44
65	2	2025-09-24 12:30:25.944552+00	22	55
66	3	2025-09-24 12:30:25.944822+00	22	51
67	2	2025-09-24 12:30:25.945083+00	22	45
68	2	2025-09-24 12:30:25.945631+00	23	38
69	2	2025-09-24 12:30:25.945912+00	23	43
70	1	2025-09-24 12:30:25.946179+00	23	51
71	1	2025-09-24 12:30:25.946737+00	24	44
72	2	2025-09-24 12:30:25.947032+00	24	48
73	1	2025-09-24 12:30:25.947335+00	24	41
\.


--
-- Data for Name: barbackend_drink; Type: TABLE DATA; Schema: public; Owner: baruser
--

COPY public.barbackend_drink (id, name, description, price, available, created_at, image, stock, updated_at, category, unavailable_threshold, low_stock_threshold) FROM stdin;
38	Still Water	Delicious Still Water	18.00	t	2025-09-24 12:30:25.935648+00	assets/StillWater.jpg	200	2025-09-24 12:30:25.935654+00	water	5	10
39	Tap Water	Delicious Tap Water	0.00	t	2025-09-24 12:30:25.935672+00	assets/TapWater.jpg	200	2025-09-24 12:30:25.935675+00	water	5	10
43	Gin & Tonic	Delicious Gin & Tonic	90.00	t	2025-09-24 12:30:25.93573+00	assets/GinTonic.jpg	40	2025-09-24 12:30:25.935732+00	cocktail	5	10
44	Mimosa	Delicious Mimosa	80.00	t	2025-09-24 12:30:25.935743+00	assets/Mimosa.png	45	2025-09-24 12:30:25.935745+00	cocktail	5	10
45	Passionfruit Martini	Delicious Passionfruit Martini	90.50	t	2025-09-24 12:30:25.935756+00	assets/PassionMartini.png	30	2025-09-24 12:30:25.935758+00	cocktail	5	10
48	Pina Colada	Delicious Pina Colada	85.00	t	2025-09-24 12:30:25.935792+00	assets/PinaColada.jpg	20	2025-09-24 12:30:25.935794+00	cocktail	5	10
49	Sunrise Mocktail	Delicious Sunrise Mocktail	60.00	t	2025-09-24 12:30:25.935805+00	assets/SunriseMocktail.jpg	30	2025-09-24 12:30:25.935807+00	mocktail	5	10
50	Irish Ale	Delicious Irish Ale	49.00	t	2025-09-24 12:30:25.935818+00	assets/IrishAle.jpg	80	2025-09-24 12:30:25.93582+00	beer	5	10
51	Black Label Beer	Delicious Black Label Beer	45.00	t	2025-09-24 12:30:25.935831+00	assets/BlackLabelBeer.jpg	20	2025-09-24 12:30:25.935833+00	beer	5	10
52	Heineken	Delicious Heineken	42.00	t	2025-09-24 12:30:25.935843+00	assets/HeinekenBeer.jpg	35	2025-09-24 12:30:25.935845+00	beer	5	10
53	Red Wine	Delicious Red Wine	120.00	t	2025-09-24 12:30:25.935861+00	assets/RedWine.jpg	40	2025-09-24 12:30:25.935863+00	wine	5	10
54	White Wine	Delicious White Wine	110.00	t	2025-09-24 12:30:25.935874+00	assets/WhiteWine.jpg	40	2025-09-24 12:30:25.935876+00	wine	5	10
55	Jagermeister	Delicious Jagermeister	50.00	t	2025-09-24 12:30:25.935887+00	assets/Jagermeister.jpg	70	2025-09-24 12:30:25.93589+00	shot	5	10
56	Whiskey Shot	Delicious Whiskey Shot	55.00	t	2025-09-24 12:30:25.9359+00	assets/WhiskeyShot.jpg	65	2025-09-24 12:30:25.935902+00	shot	5	10
57	Rosé Wine		120.00	t	2025-09-24 12:33:54.290545+00	assets/rosewine_yiY81i7.jpeg	50	2025-09-24 12:33:54.290562+00	wine	5	10
40	Coco Cola	Delicious Coco Cola	28.00	t	2025-09-24 12:30:25.935689+00	assets/Coca_Cola_on_Behance_QOErn0r.jpeg	30	2025-09-24 12:37:43.459582+00	other	5	10
41	Orange Juice	Delicious Orange Juice	25.00	t	2025-09-24 12:30:25.935702+00	assets/OrangeJuice.jpg	30	2025-09-24 12:37:48.861051+00	other	5	10
42	Espresso Martini	Delicious Espresso Martini	95.00	t	2025-09-24 12:30:25.935717+00	assets/espressomartini_314BkEA.png	50	2025-09-24 12:38:02.808544+00	cocktail	5	10
46	Peach Vodka	Delicious Peach Vodka	72.00	t	2025-09-24 12:30:25.935767+00	assets/PeachVodka.jpg	25	2025-09-24 12:38:14.173101+00	alcoholic	5	10
47	Tequila	Delicious Tequila Shot	35.00	t	2025-09-24 12:30:25.93578+00	assets/TequilaSour.png	60	2025-09-24 12:38:35.478665+00	alcoholic	5	10
\.


--
-- Data for Name: barbackend_order; Type: TABLE DATA; Schema: public; Owner: baruser
--

COPY public.barbackend_order (id, status, total_price, created_at, updated_at, user_id, note) FROM stdin;
34	pending	348.00	2025-09-24 12:30:25.947728+00	2025-09-24 12:30:26.195692+00	15	Test OTP: 123450
35	pending	278.00	2025-09-24 12:30:26.196188+00	2025-09-24 12:30:26.482023+00	16	Test OTP: 123451
36	pending	265.00	2025-09-24 12:30:26.482506+00	2025-09-24 12:30:26.750699+00	17	Test OTP: 123452
37	preparing	147.00	2025-09-24 12:30:26.751148+00	2025-09-24 12:30:27.021339+00	15	Test OTP: 123453
38	preparing	450.00	2025-09-24 12:30:27.021832+00	2025-09-24 12:30:27.308142+00	16	Test OTP: 123454
39	preparing	72.00	2025-09-24 12:30:27.308657+00	2025-09-24 12:30:27.581628+00	17	Test OTP: 123455
40	ready	742.00	2025-09-24 12:30:27.58206+00	2025-09-24 12:30:27.841716+00	15	Test OTP: 123456
41	ready	240.50	2025-09-24 12:30:27.842199+00	2025-09-24 12:30:28.10464+00	16	Test OTP: 123457
42	ready	0.00	2025-09-24 12:30:28.105188+00	2025-09-24 12:30:28.348098+00	17	Test OTP: 123458
43	completed	228.00	2025-09-24 12:30:28.348638+00	2025-09-24 12:30:28.6122+00	15	Test OTP: 123459
44	completed	480.00	2025-09-24 12:30:28.612651+00	2025-09-24 12:30:28.859826+00	16	Test OTP: 123460
45	completed	490.00	2025-09-24 12:30:28.860295+00	2025-09-24 12:30:29.134892+00	17	Test OTP: 123461
46	cancelled	353.00	2025-09-24 12:30:29.135444+00	2025-09-24 12:30:29.387236+00	15	Test OTP: 123462
47	cancelled	176.00	2025-09-24 12:30:29.387692+00	2025-09-24 12:30:29.66556+00	16	Test OTP: 123463
48	cancelled	439.00	2025-09-24 12:30:29.665977+00	2025-09-24 12:30:29.926664+00	17	Test OTP: 123464
\.


--
-- Data for Name: barbackend_orderitem; Type: TABLE DATA; Schema: public; Owner: baruser
--

COPY public.barbackend_orderitem (id, quantity, drink_id, order_id) FROM stdin;
63	1	49	34
64	4	46	34
65	3	41	35
66	3	50	35
67	2	40	35
68	3	40	36
69	1	39	36
70	2	45	36
71	3	50	37
72	3	49	38
73	3	43	38
74	1	46	39
75	2	43	40
76	4	55	40
77	4	45	40
78	3	55	41
79	1	45	41
80	3	39	42
81	2	46	43
82	3	40	43
83	4	53	44
84	2	52	45
85	2	42	45
86	3	46	45
87	3	56	46
88	2	51	46
89	2	50	46
90	1	53	47
91	2	40	47
92	2	39	47
93	4	51	48
94	4	40	48
95	3	50	48
\.


--
-- Data for Name: barbackend_orderotp; Type: TABLE DATA; Schema: public; Owner: baruser
--

COPY public.barbackend_orderotp (id, code_hash, code_plain, last_sent_at, is_used, created_at, updated_at, order_id) FROM stdin;
16	pbkdf2_sha256$1000000$KdzmtmPYpWYbVqazX5lPVV$9u4ZEC1hfx5mmFxsCZFgkByz5aBocCGXO7aEyRROa7s=	123450	\N	f	2025-09-24 12:30:26.193896+00	2025-09-24 12:30:26.193903+00	34
17	pbkdf2_sha256$1000000$cTlELYZwCcFsWaNf7Cv9kI$l7XYrhzjmr20PE7pVp9KtcgGgj5E+FqssgGctH+l5rQ=	123451	\N	f	2025-09-24 12:30:26.480517+00	2025-09-24 12:30:26.480526+00	35
18	pbkdf2_sha256$1000000$BBrTxIG3r8DaavVpMHfK4h$+vfOGKe62kd5rn2NCNt9dBtcTgMhrY7GGLI8jGHA4Rs=	123452	\N	f	2025-09-24 12:30:26.749157+00	2025-09-24 12:30:26.749165+00	36
19	pbkdf2_sha256$1000000$AEDFWQgUtDPkfJ2htCkLt0$2HmCsekw/+vPTUq2V1F38+xUJYpJRmPzbmshKszZqtA=	123453	\N	f	2025-09-24 12:30:27.019788+00	2025-09-24 12:30:27.019796+00	37
20	pbkdf2_sha256$1000000$JdQBk4eO7nlb3D0twExB0j$LROcYQuxkwQy0uih7bQe2Ngzq2P+NocGedr3+0qlurQ=	123454	\N	f	2025-09-24 12:30:27.306458+00	2025-09-24 12:30:27.306467+00	38
21	pbkdf2_sha256$1000000$8flI6bAAu7yARPLLzzXm2I$FW1Ei4n1E3VetNMCc1Pg+uFrnjNiSCMNHWsxOFkaoec=	123455	\N	f	2025-09-24 12:30:27.579908+00	2025-09-24 12:30:27.579918+00	39
22	pbkdf2_sha256$1000000$LZTbCwJcD6Y552ZDILL7Od$e5fuhnhMVhXz4hPeZYnkOPUGmX6s8b0fxfKX5Df542U=	123456	\N	f	2025-09-24 12:30:27.839919+00	2025-09-24 12:30:27.839927+00	40
23	pbkdf2_sha256$1000000$HhalFqPLiztjOpj736sWq7$Rx/lYM9lUJDc6g4nkPW0ZVLyH0IbmMRBF+D5srDicCQ=	123457	\N	f	2025-09-24 12:30:28.102446+00	2025-09-24 12:30:28.102458+00	41
24	pbkdf2_sha256$1000000$1t51wgim9VABxnJIzsyUFU$0yWuNNwtrLYD4y4+dPgYirnipetfL5k3nurOm6uZJt0=	123458	\N	f	2025-09-24 12:30:28.346262+00	2025-09-24 12:30:28.346271+00	42
25	pbkdf2_sha256$1000000$KSh2fMOPkks4PvAg2lw4JU$yYZTjC4KJVPI6U4Frol33Ul+FVXq+kZatSVwIgIt69g=	123459	\N	f	2025-09-24 12:30:28.610682+00	2025-09-24 12:30:28.61069+00	43
26	pbkdf2_sha256$1000000$vUk58S2tsHwS3yVeOGTsfx$AqvOBeiN1QIPjykvfno1eAw5DILDuOh1ChaFBWVM8AI=	123460	\N	f	2025-09-24 12:30:28.858211+00	2025-09-24 12:30:28.858219+00	44
27	pbkdf2_sha256$1000000$d8V8O3uE0itjefvBPFi6d2$jFFLR/ots8QKT0EsZVGLu/3e8Yt6bv+5AP1j09Gu6xs=	123461	\N	f	2025-09-24 12:30:29.132534+00	2025-09-24 12:30:29.132545+00	45
28	pbkdf2_sha256$1000000$IK0YIgu9uQYlxynlLlBFDa$m04hDTPKuDKn/We8vnFppHmPglN31cYygdNeoE3XKnU=	123462	\N	f	2025-09-24 12:30:29.385688+00	2025-09-24 12:30:29.385696+00	46
29	pbkdf2_sha256$1000000$SKrahEEX7h7N2F8Ie6WxcH$9O6H8UcN1koI/vzA+voJE/9dJvt3Q1JzATx50Z8uYiM=	123463	\N	f	2025-09-24 12:30:29.664069+00	2025-09-24 12:30:29.664078+00	47
30	pbkdf2_sha256$1000000$XMP5bddXXVDgZY7jwDGGAk$vyPbodjX6677VJmEUZuB8SkVTZKm7cWjMt0csA+T8GQ=	123464	\N	f	2025-09-24 12:30:29.92504+00	2025-09-24 12:30:29.92505+00	48
\.


--
-- Data for Name: barbackend_user; Type: TABLE DATA; Schema: public; Owner: baruser
--

COPY public.barbackend_user (id, username, email, role, created_at, date_joined, is_active, is_staff, is_superuser, last_login, password, is_admin) FROM stdin;
14	default_staff	staff@example.com	staff	2025-09-24 12:30:24.393956+00	2025-09-24 12:30:24.393947+00	t	t	f	\N	pbkdf2_sha256$1000000$jn8MTsXXwRc1NqKOBpyeqN$KyFsL7LfEnWyGitJ+h+hPSLMcqzjTple8s5TpaGfN4A=	f
15	alice	alice@example.com	customer	2025-09-24 12:30:24.652607+00	2025-09-24 12:30:24.652598+00	t	f	f	\N	pbkdf2_sha256$1000000$W8VXuBdV9KVsurqRmMPDwf$OrA8Kk406p8u+OgdTCNSINqfDC0A21ByiODzjRm9szI=	f
16	bob	bob@example.com	customer	2025-09-24 12:30:24.906359+00	2025-09-24 12:30:24.90635+00	t	f	f	\N	pbkdf2_sha256$1000000$Z5AlaYQHtuGwFTRIyIjU6N$yXAlKq9EKFGrdmixPnD67f7MofHoSPBEeNZEV4lBW4M=	f
17	carol	carol@example.com	customer	2025-09-24 12:30:25.147423+00	2025-09-24 12:30:25.147411+00	t	f	f	\N	pbkdf2_sha256$1000000$7kRgNWqP1DghSSDvt303Xo$rXBIRGJqJcNTSo/xztfLTFovAFC2aQg1UtB0Rj72AVE=	f
18	admin	admin@example.com	staff	2025-09-24 12:30:25.411986+00	2025-09-24 12:30:25.411978+00	t	t	t	\N	pbkdf2_sha256$1000000$yTiAk6yYnqTT2ex8BrIQFx$fTJI3saW+3WO2IYzGU7vffOmDRdGSAV7Ph/yiSWVSPw=	t
19	dave	dave@example.com	staff	2025-09-24 12:30:25.67061+00	2025-09-24 12:30:25.670601+00	t	f	f	\N	pbkdf2_sha256$1000000$aLKqhPj4ACu3jK7mzMnqZG$L7XDwQktRE7w02Ofc5MkTgQNv5FjrOaNw4vTMte14Dc=	f
20	eve	eve@example.com	staff	2025-09-24 12:30:25.932483+00	2025-09-24 12:30:25.932471+00	t	f	f	\N	pbkdf2_sha256$1000000$hMvIw5Kq80IW0Su9j5hSj1$YxjqJM4i5E7opKNCnJwMcXBaBK5ctTJWbFFlDlx0Yyo=	f
\.


--
-- Data for Name: barbackend_user_groups; Type: TABLE DATA; Schema: public; Owner: baruser
--

COPY public.barbackend_user_groups (id, user_id, group_id) FROM stdin;
\.


--
-- Data for Name: barbackend_user_user_permissions; Type: TABLE DATA; Schema: public; Owner: baruser
--

COPY public.barbackend_user_user_permissions (id, user_id, permission_id) FROM stdin;
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: baruser
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: baruser
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	permission
3	auth	group
4	auth	user
5	contenttypes	contenttype
6	sessions	session
7	barbackend	drink
8	barbackend	order
9	barbackend	user
10	barbackend	orderitem
11	barbackend	cart
12	barbackend	cartitem
13	barbackend	orderotp
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: baruser
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2025-08-11 15:40:54.88937+00
2	auth	0001_initial	2025-08-11 15:40:55.678309+00
3	admin	0001_initial	2025-08-11 15:40:56.500005+00
4	admin	0002_logentry_remove_auto_add	2025-08-11 15:40:56.518439+00
5	admin	0003_logentry_add_action_flag_choices	2025-08-11 15:40:56.549361+00
6	contenttypes	0002_remove_content_type_name	2025-08-11 15:40:56.568894+00
7	auth	0002_alter_permission_name_max_length	2025-08-11 15:40:56.586827+00
8	auth	0003_alter_user_email_max_length	2025-08-11 15:40:56.60928+00
9	auth	0004_alter_user_username_opts	2025-08-11 15:40:56.629407+00
10	auth	0005_alter_user_last_login_null	2025-08-11 15:40:56.650026+00
11	auth	0006_require_contenttypes_0002	2025-08-11 15:40:56.665927+00
12	auth	0007_alter_validators_add_error_messages	2025-08-11 15:40:56.682749+00
13	auth	0008_alter_user_username_max_length	2025-08-11 15:40:56.746834+00
14	auth	0009_alter_user_last_name_max_length	2025-08-11 15:40:56.764072+00
15	auth	0010_alter_group_name_max_length	2025-08-11 15:40:56.786003+00
16	auth	0011_update_proxy_permissions	2025-08-11 15:40:56.804609+00
17	auth	0012_alter_user_first_name_max_length	2025-08-11 15:40:56.827781+00
18	barbackend	0001_initial	2025-08-11 15:40:58.363915+00
19	barbackend	0002_alter_order_status	2025-08-11 15:40:58.378159+00
20	sessions	0001_initial	2025-08-11 15:40:58.61434+00
21	barbackend	0003_drink_image	2025-08-18 13:25:17.100592+00
22	barbackend	0003_cart_note	2025-08-18 13:56:31.552807+00
23	barbackend	0004_order_note	2025-08-18 13:56:31.596092+00
24	barbackend	0005_merge_0003_drink_image_0004_order_note	2025-08-18 13:56:31.621633+00
25	barbackend	0006_remove_cart_note_remove_order_note	2025-08-18 18:52:07.101557+00
26	barbackend	0006_remove_cart_note_remove_order_note_drink_stock_and_more	2025-08-19 06:22:36.724856+00
27	barbackend	0007_drink_category	2025-08-19 06:22:36.796749+00
28	barbackend	0008_alter_drink_image	2025-08-19 16:10:48.524514+00
29	barbackend	0009_alter_drink_image	2025-08-19 19:15:11.572499+00
30	barbackend	0008_cart_note_order_note	2025-08-20 06:38:06.75994+00
31	barbackend	0009_merge_20250819_1942	2025-08-20 07:22:20.81962+00
32	barbackend	0010_alter_drink_image	2025-08-20 07:22:20.84228+00
33	barbackend	0011_alter_drink_image	2025-08-22 07:44:14.305754+00
34	barbackend	0009_merge_20250822_2043	2025-08-22 20:44:03.445618+00
35	barbackend	0012_orderotp	2025-09-03 20:01:10.917917+00
36	barbackend	0013_remove_orderotp_attempts_remove_orderotp_expires_at_and_more	2025-09-03 20:01:10.941204+00
37	barbackend	0014_uniq_active_otp_code_plain	2025-09-03 20:01:11.000984+00
38	barbackend	0015_merge_20250903_1347	2025-09-03 20:01:11.013295+00
39	barbackend	0016_alter_user_managers_remove_user_password_hash_and_more	2025-09-03 20:01:11.381331+00
40	barbackend	0017_drink_low_stock_threshold	2025-09-17 09:51:44.991045+00
41	barbackend	0018_user_is_admin	2025-09-17 09:51:45.028066+00
42	barbackend	0019_rename_low_stock_threshold_add_low_stock_threshold	2025-09-17 09:51:45.04584+00
43	barbackend	0020_alter_drink_unavailable_threshold	2025-09-17 09:51:45.069242+00
44	barbackend	0021_cart_updated_at	2025-09-24 10:48:32.652024+00
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: baruser
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
\.


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: baruser
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: baruser
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: baruser
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 52, true);


--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: baruser
--

SELECT pg_catalog.setval('public.auth_user_groups_id_seq', 1, false);


--
-- Name: auth_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: baruser
--

SELECT pg_catalog.setval('public.auth_user_id_seq', 1, false);


--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: baruser
--

SELECT pg_catalog.setval('public.auth_user_user_permissions_id_seq', 1, false);


--
-- Name: barbackend_cart_id_seq; Type: SEQUENCE SET; Schema: public; Owner: baruser
--

SELECT pg_catalog.setval('public.barbackend_cart_id_seq', 24, true);


--
-- Name: barbackend_cartitem_id_seq; Type: SEQUENCE SET; Schema: public; Owner: baruser
--

SELECT pg_catalog.setval('public.barbackend_cartitem_id_seq', 73, true);


--
-- Name: barbackend_drink_id_seq; Type: SEQUENCE SET; Schema: public; Owner: baruser
--

SELECT pg_catalog.setval('public.barbackend_drink_id_seq', 57, true);


--
-- Name: barbackend_order_id_seq; Type: SEQUENCE SET; Schema: public; Owner: baruser
--

SELECT pg_catalog.setval('public.barbackend_order_id_seq', 48, true);


--
-- Name: barbackend_orderitem_id_seq; Type: SEQUENCE SET; Schema: public; Owner: baruser
--

SELECT pg_catalog.setval('public.barbackend_orderitem_id_seq', 95, true);


--
-- Name: barbackend_orderotp_id_seq; Type: SEQUENCE SET; Schema: public; Owner: baruser
--

SELECT pg_catalog.setval('public.barbackend_orderotp_id_seq', 30, true);


--
-- Name: barbackend_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: baruser
--

SELECT pg_catalog.setval('public.barbackend_user_groups_id_seq', 1, false);


--
-- Name: barbackend_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: baruser
--

SELECT pg_catalog.setval('public.barbackend_user_id_seq', 20, true);


--
-- Name: barbackend_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: baruser
--

SELECT pg_catalog.setval('public.barbackend_user_user_permissions_id_seq', 1, false);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: baruser
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 1, false);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: baruser
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 13, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: baruser
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 44, true);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: baruser
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: baruser
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: baruser
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: baruser
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: baruser
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: baruser
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: baruser
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_user_id_group_id_94350c0c_uniq; Type: CONSTRAINT; Schema: public; Owner: baruser
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id);


--
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: public; Owner: baruser
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: baruser
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_permission_id_14a6b632_uniq; Type: CONSTRAINT; Schema: public; Owner: baruser
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id);


--
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: public; Owner: baruser
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- Name: barbackend_cart barbackend_cart_pkey; Type: CONSTRAINT; Schema: public; Owner: baruser
--

ALTER TABLE ONLY public.barbackend_cart
    ADD CONSTRAINT barbackend_cart_pkey PRIMARY KEY (id);


--
-- Name: barbackend_cart barbackend_cart_user_id_key; Type: CONSTRAINT; Schema: public; Owner: baruser
--

ALTER TABLE ONLY public.barbackend_cart
    ADD CONSTRAINT barbackend_cart_user_id_key UNIQUE (user_id);


--
-- Name: barbackend_cartitem barbackend_cartitem_cart_id_drink_id_5b25342a_uniq; Type: CONSTRAINT; Schema: public; Owner: baruser
--

ALTER TABLE ONLY public.barbackend_cartitem
    ADD CONSTRAINT barbackend_cartitem_cart_id_drink_id_5b25342a_uniq UNIQUE (cart_id, drink_id);


--
-- Name: barbackend_cartitem barbackend_cartitem_pkey; Type: CONSTRAINT; Schema: public; Owner: baruser
--

ALTER TABLE ONLY public.barbackend_cartitem
    ADD CONSTRAINT barbackend_cartitem_pkey PRIMARY KEY (id);


--
-- Name: barbackend_drink barbackend_drink_pkey; Type: CONSTRAINT; Schema: public; Owner: baruser
--

ALTER TABLE ONLY public.barbackend_drink
    ADD CONSTRAINT barbackend_drink_pkey PRIMARY KEY (id);


--
-- Name: barbackend_order barbackend_order_pkey; Type: CONSTRAINT; Schema: public; Owner: baruser
--

ALTER TABLE ONLY public.barbackend_order
    ADD CONSTRAINT barbackend_order_pkey PRIMARY KEY (id);


--
-- Name: barbackend_orderitem barbackend_orderitem_pkey; Type: CONSTRAINT; Schema: public; Owner: baruser
--

ALTER TABLE ONLY public.barbackend_orderitem
    ADD CONSTRAINT barbackend_orderitem_pkey PRIMARY KEY (id);


--
-- Name: barbackend_orderotp barbackend_orderotp_order_id_key; Type: CONSTRAINT; Schema: public; Owner: baruser
--

ALTER TABLE ONLY public.barbackend_orderotp
    ADD CONSTRAINT barbackend_orderotp_order_id_key UNIQUE (order_id);


--
-- Name: barbackend_orderotp barbackend_orderotp_pkey; Type: CONSTRAINT; Schema: public; Owner: baruser
--

ALTER TABLE ONLY public.barbackend_orderotp
    ADD CONSTRAINT barbackend_orderotp_pkey PRIMARY KEY (id);


--
-- Name: barbackend_user barbackend_user_email_key; Type: CONSTRAINT; Schema: public; Owner: baruser
--

ALTER TABLE ONLY public.barbackend_user
    ADD CONSTRAINT barbackend_user_email_key UNIQUE (email);


--
-- Name: barbackend_user_groups barbackend_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: baruser
--

ALTER TABLE ONLY public.barbackend_user_groups
    ADD CONSTRAINT barbackend_user_groups_pkey PRIMARY KEY (id);


--
-- Name: barbackend_user_groups barbackend_user_groups_user_id_group_id_302d3e94_uniq; Type: CONSTRAINT; Schema: public; Owner: baruser
--

ALTER TABLE ONLY public.barbackend_user_groups
    ADD CONSTRAINT barbackend_user_groups_user_id_group_id_302d3e94_uniq UNIQUE (user_id, group_id);


--
-- Name: barbackend_user barbackend_user_pkey; Type: CONSTRAINT; Schema: public; Owner: baruser
--

ALTER TABLE ONLY public.barbackend_user
    ADD CONSTRAINT barbackend_user_pkey PRIMARY KEY (id);


--
-- Name: barbackend_user_user_permissions barbackend_user_user_per_user_id_permission_id_e070f34a_uniq; Type: CONSTRAINT; Schema: public; Owner: baruser
--

ALTER TABLE ONLY public.barbackend_user_user_permissions
    ADD CONSTRAINT barbackend_user_user_per_user_id_permission_id_e070f34a_uniq UNIQUE (user_id, permission_id);


--
-- Name: barbackend_user_user_permissions barbackend_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: baruser
--

ALTER TABLE ONLY public.barbackend_user_user_permissions
    ADD CONSTRAINT barbackend_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: barbackend_user barbackend_user_username_key; Type: CONSTRAINT; Schema: public; Owner: baruser
--

ALTER TABLE ONLY public.barbackend_user
    ADD CONSTRAINT barbackend_user_username_key UNIQUE (username);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: baruser
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: baruser
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: baruser
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: baruser
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: baruser
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: baruser
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: baruser
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: baruser
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: baruser
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: auth_user_groups_group_id_97559544; Type: INDEX; Schema: public; Owner: baruser
--

CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);


--
-- Name: auth_user_groups_user_id_6a12ed8b; Type: INDEX; Schema: public; Owner: baruser
--

CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);


--
-- Name: auth_user_user_permissions_permission_id_1fbb5f2c; Type: INDEX; Schema: public; Owner: baruser
--

CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);


--
-- Name: auth_user_user_permissions_user_id_a95ead1b; Type: INDEX; Schema: public; Owner: baruser
--

CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);


--
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: public; Owner: baruser
--

CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);


--
-- Name: barbackend_cartitem_cart_id_1981aa35; Type: INDEX; Schema: public; Owner: baruser
--

CREATE INDEX barbackend_cartitem_cart_id_1981aa35 ON public.barbackend_cartitem USING btree (cart_id);


--
-- Name: barbackend_cartitem_drink_id_45acf3f2; Type: INDEX; Schema: public; Owner: baruser
--

CREATE INDEX barbackend_cartitem_drink_id_45acf3f2 ON public.barbackend_cartitem USING btree (drink_id);


--
-- Name: barbackend_order_user_id_4bc7d8b6; Type: INDEX; Schema: public; Owner: baruser
--

CREATE INDEX barbackend_order_user_id_4bc7d8b6 ON public.barbackend_order USING btree (user_id);


--
-- Name: barbackend_orderitem_drink_id_3130a7e7; Type: INDEX; Schema: public; Owner: baruser
--

CREATE INDEX barbackend_orderitem_drink_id_3130a7e7 ON public.barbackend_orderitem USING btree (drink_id);


--
-- Name: barbackend_orderitem_order_id_f9735e29; Type: INDEX; Schema: public; Owner: baruser
--

CREATE INDEX barbackend_orderitem_order_id_f9735e29 ON public.barbackend_orderitem USING btree (order_id);


--
-- Name: barbackend_user_email_759a19ed_like; Type: INDEX; Schema: public; Owner: baruser
--

CREATE INDEX barbackend_user_email_759a19ed_like ON public.barbackend_user USING btree (email varchar_pattern_ops);


--
-- Name: barbackend_user_groups_group_id_6de77435; Type: INDEX; Schema: public; Owner: baruser
--

CREATE INDEX barbackend_user_groups_group_id_6de77435 ON public.barbackend_user_groups USING btree (group_id);


--
-- Name: barbackend_user_groups_user_id_874defee; Type: INDEX; Schema: public; Owner: baruser
--

CREATE INDEX barbackend_user_groups_user_id_874defee ON public.barbackend_user_groups USING btree (user_id);


--
-- Name: barbackend_user_user_permissions_permission_id_052a236b; Type: INDEX; Schema: public; Owner: baruser
--

CREATE INDEX barbackend_user_user_permissions_permission_id_052a236b ON public.barbackend_user_user_permissions USING btree (permission_id);


--
-- Name: barbackend_user_user_permissions_user_id_3dff7233; Type: INDEX; Schema: public; Owner: baruser
--

CREATE INDEX barbackend_user_user_permissions_user_id_3dff7233 ON public.barbackend_user_user_permissions USING btree (user_id);


--
-- Name: barbackend_user_username_33deff3a_like; Type: INDEX; Schema: public; Owner: baruser
--

CREATE INDEX barbackend_user_username_33deff3a_like ON public.barbackend_user USING btree (username varchar_pattern_ops);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: baruser
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: baruser
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: baruser
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: baruser
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: uniq_active_otp_code_plain; Type: INDEX; Schema: public; Owner: baruser
--

CREATE UNIQUE INDEX uniq_active_otp_code_plain ON public.barbackend_orderotp USING btree (code_plain) WHERE (NOT is_used);


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: baruser
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: baruser
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: baruser
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_group_id_97559544_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: baruser
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_user_id_6a12ed8b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: baruser
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: baruser
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: baruser
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: barbackend_cart barbackend_cart_user_id_ad62b38c_fk_barbackend_user_id; Type: FK CONSTRAINT; Schema: public; Owner: baruser
--

ALTER TABLE ONLY public.barbackend_cart
    ADD CONSTRAINT barbackend_cart_user_id_ad62b38c_fk_barbackend_user_id FOREIGN KEY (user_id) REFERENCES public.barbackend_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: barbackend_cartitem barbackend_cartitem_cart_id_1981aa35_fk_barbackend_cart_id; Type: FK CONSTRAINT; Schema: public; Owner: baruser
--

ALTER TABLE ONLY public.barbackend_cartitem
    ADD CONSTRAINT barbackend_cartitem_cart_id_1981aa35_fk_barbackend_cart_id FOREIGN KEY (cart_id) REFERENCES public.barbackend_cart(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: barbackend_cartitem barbackend_cartitem_drink_id_45acf3f2_fk_barbackend_drink_id; Type: FK CONSTRAINT; Schema: public; Owner: baruser
--

ALTER TABLE ONLY public.barbackend_cartitem
    ADD CONSTRAINT barbackend_cartitem_drink_id_45acf3f2_fk_barbackend_drink_id FOREIGN KEY (drink_id) REFERENCES public.barbackend_drink(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: barbackend_order barbackend_order_user_id_4bc7d8b6_fk_barbackend_user_id; Type: FK CONSTRAINT; Schema: public; Owner: baruser
--

ALTER TABLE ONLY public.barbackend_order
    ADD CONSTRAINT barbackend_order_user_id_4bc7d8b6_fk_barbackend_user_id FOREIGN KEY (user_id) REFERENCES public.barbackend_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: barbackend_orderitem barbackend_orderitem_drink_id_3130a7e7_fk_barbackend_drink_id; Type: FK CONSTRAINT; Schema: public; Owner: baruser
--

ALTER TABLE ONLY public.barbackend_orderitem
    ADD CONSTRAINT barbackend_orderitem_drink_id_3130a7e7_fk_barbackend_drink_id FOREIGN KEY (drink_id) REFERENCES public.barbackend_drink(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: barbackend_orderitem barbackend_orderitem_order_id_f9735e29_fk_barbackend_order_id; Type: FK CONSTRAINT; Schema: public; Owner: baruser
--

ALTER TABLE ONLY public.barbackend_orderitem
    ADD CONSTRAINT barbackend_orderitem_order_id_f9735e29_fk_barbackend_order_id FOREIGN KEY (order_id) REFERENCES public.barbackend_order(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: barbackend_orderotp barbackend_orderotp_order_id_85a19be7_fk_barbackend_order_id; Type: FK CONSTRAINT; Schema: public; Owner: baruser
--

ALTER TABLE ONLY public.barbackend_orderotp
    ADD CONSTRAINT barbackend_orderotp_order_id_85a19be7_fk_barbackend_order_id FOREIGN KEY (order_id) REFERENCES public.barbackend_order(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: barbackend_user_groups barbackend_user_groups_group_id_6de77435_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: baruser
--

ALTER TABLE ONLY public.barbackend_user_groups
    ADD CONSTRAINT barbackend_user_groups_group_id_6de77435_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: barbackend_user_groups barbackend_user_groups_user_id_874defee_fk_barbackend_user_id; Type: FK CONSTRAINT; Schema: public; Owner: baruser
--

ALTER TABLE ONLY public.barbackend_user_groups
    ADD CONSTRAINT barbackend_user_groups_user_id_874defee_fk_barbackend_user_id FOREIGN KEY (user_id) REFERENCES public.barbackend_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: barbackend_user_user_permissions barbackend_user_user_permission_id_052a236b_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: baruser
--

ALTER TABLE ONLY public.barbackend_user_user_permissions
    ADD CONSTRAINT barbackend_user_user_permission_id_052a236b_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: barbackend_user_user_permissions barbackend_user_user_user_id_3dff7233_fk_barbacken; Type: FK CONSTRAINT; Schema: public; Owner: baruser
--

ALTER TABLE ONLY public.barbackend_user_user_permissions
    ADD CONSTRAINT barbackend_user_user_user_id_3dff7233_fk_barbacken FOREIGN KEY (user_id) REFERENCES public.barbackend_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: baruser
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: baruser
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: SCHEMA public; Type: ACL; Schema: -; Owner: baruser
--

REVOKE USAGE ON SCHEMA public FROM PUBLIC;
GRANT ALL ON SCHEMA public TO PUBLIC;


--
-- PostgreSQL database dump complete
--

\unrestrict U1H5thgiqNALB7cyghGbtyPUFdV9jGJmNxvXs2CvVERUO4jTyhsCEBa0LUCZrCU

