--
-- PostgreSQL database dump
--

\restrict 4C9dSDZ1yyiYKgc9Sqbv042bIggXT7TuOIuhN0Trb4GTHm4isYkTUXUdns5VZ8p

-- Dumped from database version 16.10 (Ubuntu 16.10-0ubuntu0.24.04.1)
-- Dumped by pg_dump version 16.10 (Ubuntu 16.10-0ubuntu0.24.04.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: baruser
--

-- *not* creating schema, since initdb creates it



SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: baruser
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);



--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: baruser
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: baruser
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);



--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: baruser
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: baruser
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);



--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: baruser
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user; Type: TABLE; Schema: public; Owner: baruser
--

CREATE TABLE public.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);



--
-- Name: auth_user_groups; Type: TABLE; Schema: public; Owner: baruser
--

CREATE TABLE public.auth_user_groups (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);



--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: baruser
--

ALTER TABLE public.auth_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: public; Owner: baruser
--

ALTER TABLE public.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_user_permissions; Type: TABLE; Schema: public; Owner: baruser
--

CREATE TABLE public.auth_user_user_permissions (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);



--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: baruser
--

ALTER TABLE public.auth_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: barbackend_cart; Type: TABLE; Schema: public; Owner: baruser
--

CREATE TABLE public.barbackend_cart (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    user_id bigint NOT NULL,
    note text NOT NULL,
    updated_at timestamp with time zone NOT NULL
);



--
-- Name: barbackend_cart_id_seq; Type: SEQUENCE; Schema: public; Owner: baruser
--

ALTER TABLE public.barbackend_cart ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.barbackend_cart_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: barbackend_cartitem; Type: TABLE; Schema: public; Owner: baruser
--

CREATE TABLE public.barbackend_cartitem (
    id bigint NOT NULL,
    quantity integer NOT NULL,
    added_at timestamp with time zone NOT NULL,
    cart_id bigint NOT NULL,
    drink_id bigint NOT NULL,
    CONSTRAINT barbackend_cartitem_quantity_check CHECK ((quantity >= 0))
);



--
-- Name: barbackend_cartitem_id_seq; Type: SEQUENCE; Schema: public; Owner: baruser
--

ALTER TABLE public.barbackend_cartitem ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.barbackend_cartitem_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: barbackend_drink; Type: TABLE; Schema: public; Owner: baruser
--

CREATE TABLE public.barbackend_drink (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    description text NOT NULL,
    price numeric(6,2) NOT NULL,
    available boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    image character varying(100) NOT NULL,
    stock integer NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    category character varying(50) NOT NULL,
    unavailable_threshold integer DEFAULT 5,
    low_stock_threshold integer NOT NULL,
    CONSTRAINT barbackend_drink_low_stock_threshold_check CHECK ((low_stock_threshold >= 0)),
    CONSTRAINT barbackend_drink_stock_check CHECK ((stock >= 0))
);



--
-- Name: barbackend_drink_id_seq; Type: SEQUENCE; Schema: public; Owner: baruser
--

ALTER TABLE public.barbackend_drink ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.barbackend_drink_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: barbackend_order; Type: TABLE; Schema: public; Owner: baruser
--

CREATE TABLE public.barbackend_order (
    id bigint NOT NULL,
    status character varying(30) NOT NULL,
    total_price numeric(8,2) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    user_id bigint NOT NULL,
    note text NOT NULL
);



--
-- Name: barbackend_order_id_seq; Type: SEQUENCE; Schema: public; Owner: baruser
--

ALTER TABLE public.barbackend_order ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.barbackend_order_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: barbackend_orderitem; Type: TABLE; Schema: public; Owner: baruser
--

CREATE TABLE public.barbackend_orderitem (
    id bigint NOT NULL,
    quantity integer NOT NULL,
    drink_id bigint NOT NULL,
    order_id bigint NOT NULL,
    CONSTRAINT barbackend_orderitem_quantity_check CHECK ((quantity >= 0))
);



--
-- Name: barbackend_orderitem_id_seq; Type: SEQUENCE; Schema: public; Owner: baruser
--

ALTER TABLE public.barbackend_orderitem ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.barbackend_orderitem_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: barbackend_orderotp; Type: TABLE; Schema: public; Owner: baruser
--

CREATE TABLE public.barbackend_orderotp (
    id bigint NOT NULL,
    code_hash character varying(128) NOT NULL,
    code_plain character varying(10) NOT NULL,
    last_sent_at timestamp with time zone,
    is_used boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    order_id bigint NOT NULL
);



--
-- Name: barbackend_orderotp_id_seq; Type: SEQUENCE; Schema: public; Owner: baruser
--

ALTER TABLE public.barbackend_orderotp ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.barbackend_orderotp_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: barbackend_user; Type: TABLE; Schema: public; Owner: baruser
--

CREATE TABLE public.barbackend_user (
    id bigint NOT NULL,
    username character varying(50) NOT NULL,
    email character varying(254) NOT NULL,
    role character varying(20) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    is_active boolean NOT NULL,
    is_staff boolean NOT NULL,
    is_superuser boolean NOT NULL,
    last_login timestamp with time zone,
    password character varying(128) NOT NULL,
    is_admin boolean NOT NULL
);



--
-- Name: barbackend_user_groups; Type: TABLE; Schema: public; Owner: baruser
--

CREATE TABLE public.barbackend_user_groups (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    group_id integer NOT NULL
);



--
-- Name: barbackend_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: baruser
--

ALTER TABLE public.barbackend_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.barbackend_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: barbackend_user_id_seq; Type: SEQUENCE; Schema: public; Owner: baruser
--

ALTER TABLE public.barbackend_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.barbackend_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: barbackend_user_user_permissions; Type: TABLE; Schema: public; Owner: baruser
--

CREATE TABLE public.barbackend_user_user_permissions (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    permission_id integer NOT NULL
);



--
-- Name: barbackend_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: baruser
--

ALTER TABLE public.barbackend_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.barbackend_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: baruser
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);



--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: baruser
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: baruser
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);



--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: baruser
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: baruser
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);



--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: baruser
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: baruser
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);



--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: baruser
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: baruser
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: baruser
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	2	add_permission
6	Can change permission	2	change_permission
7	Can delete permission	2	delete_permission
8	Can view permission	2	view_permission
9	Can add group	3	add_group
10	Can change group	3	change_group
11	Can delete group	3	delete_group
12	Can view group	3	view_group
13	Can add content type	4	add_contenttype
14	Can change content type	4	change_contenttype
15	Can delete content type	4	delete_contenttype
16	Can view content type	4	view_contenttype
17	Can add session	5	add_session
18	Can change session	5	change_session
19	Can delete session	5	delete_session
20	Can view session	5	view_session
21	Can add drink	6	add_drink
22	Can change drink	6	change_drink
23	Can delete drink	6	delete_drink
24	Can view drink	6	view_drink
25	Can add order	7	add_order
26	Can change order	7	change_order
27	Can delete order	7	delete_order
28	Can view order	7	view_order
29	Can add user	8	add_user
30	Can change user	8	change_user
31	Can delete user	8	delete_user
32	Can view user	8	view_user
33	Can add order item	9	add_orderitem
34	Can change order item	9	change_orderitem
35	Can delete order item	9	delete_orderitem
36	Can view order item	9	view_orderitem
37	Can add cart	10	add_cart
38	Can change cart	10	change_cart
39	Can delete cart	10	delete_cart
40	Can view cart	10	view_cart
41	Can add cart item	11	add_cartitem
42	Can change cart item	11	change_cartitem
43	Can delete cart item	11	delete_cartitem
44	Can view cart item	11	view_cartitem
45	Can add order otp	12	add_orderotp
46	Can change order otp	12	change_orderotp
47	Can delete order otp	12	delete_orderotp
48	Can view order otp	12	view_orderotp
49	Can add content type	5	add_contenttype
50	Can change content type	5	change_contenttype
51	Can delete content type	5	delete_contenttype
52	Can view content type	5	view_contenttype
53	Can add session	6	add_session
54	Can change session	6	change_session
55	Can delete session	6	delete_session
56	Can view session	6	view_session
57	Can add drink	7	add_drink
58	Can change drink	7	change_drink
59	Can delete drink	7	delete_drink
60	Can view drink	7	view_drink
61	Can add order	8	add_order
62	Can change order	8	change_order
63	Can delete order	8	delete_order
64	Can view order	8	view_order
65	Can add user	9	add_user
66	Can change user	9	change_user
67	Can delete user	9	delete_user
68	Can view user	9	view_user
69	Can add order item	10	add_orderitem
70	Can change order item	10	change_orderitem
71	Can delete order item	10	delete_orderitem
72	Can view order item	10	view_orderitem
73	Can add cart	11	add_cart
74	Can change cart	11	change_cart
75	Can delete cart	11	delete_cart
76	Can view cart	11	view_cart
77	Can add cart item	12	add_cartitem
78	Can change cart item	12	change_cartitem
79	Can delete cart item	12	delete_cartitem
80	Can view cart item	12	view_cartitem
81	Can add order otp	13	add_orderotp
82	Can change order otp	13	change_orderotp
83	Can delete order otp	13	delete_orderotp
84	Can view order otp	13	view_orderotp
\.


--
-- Data for Name: auth_user; Type: TABLE DATA; Schema: public; Owner: baruser
--

COPY public.auth_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined) FROM stdin;
\.


--
-- Data for Name: auth_user_groups; Type: TABLE DATA; Schema: public; Owner: baruser
--

COPY public.auth_user_groups (id, user_id, group_id) FROM stdin;
\.


--
-- Data for Name: auth_user_user_permissions; Type: TABLE DATA; Schema: public; Owner: baruser
--

COPY public.auth_user_user_permissions (id, user_id, permission_id) FROM stdin;
\.


--
-- Data for Name: barbackend_cart; Type: TABLE DATA; Schema: public; Owner: baruser
--

COPY public.barbackend_cart (id, created_at, user_id, note, updated_at) FROM stdin;
4	2025-09-10 13:30:42.43896+02	2		2025-09-22 22:48:08.671409+02
3	2025-09-10 13:06:05.00534+02	1		2025-09-22 22:48:08.671409+02
6	2025-09-10 13:32:52.75631+02	3		2025-09-22 22:48:08.671409+02
8	2025-09-18 14:38:15.150254+02	5		2025-09-22 22:48:08.671409+02
\.


--
-- Data for Name: barbackend_cartitem; Type: TABLE DATA; Schema: public; Owner: baruser
--

COPY public.barbackend_cartitem (id, quantity, added_at, cart_id, drink_id) FROM stdin;
5	20	2025-09-10 13:32:57.158496+02	6	1
\.


--
-- Data for Name: barbackend_drink; Type: TABLE DATA; Schema: public; Owner: baruser
--

COPY public.barbackend_drink (id, name, description, price, available, created_at, image, stock, updated_at, category, unavailable_threshold, low_stock_threshold) FROM stdin;
1	Espresso Martini		80.00	t	2025-08-20 18:18:56.409879+02	assets/cocktail.png	10	2025-08-20 18:18:56.409904+02	Alcoholic	5	10
2	Irish Ale		50.00	t	2025-08-20 18:21:51.568935+02	assets/irishale.png	10	2025-08-20 18:21:51.568951+02	Alcoholic	5	10
5	Passion Fruit Lemonade		25.00	t	2025-08-22 10:18:05.001091+02	assets/passionfruit.jpg	15	2025-08-22 10:18:05.001103+02	Non-Alcoholic	5	10
7	Peach Vodka		60.00	t	2025-08-22 10:23:35.900439+02	assets/peachvodka.jpg	10	2025-08-22 10:23:35.900448+02	Alcoholic	5	10
8	Passionfruit Martini		50.00	t	2025-08-22 10:25:42.814953+02	assets/passionmartini.png	10	2025-08-22 10:25:42.814962+02	Alcoholic	5	10
9	Gin & Tonic		35.00	t	2025-08-22 10:32:56.958632+02	assets/gintonic.jpg	8	2025-08-22 10:32:56.958643+02	Alcoholic	5	10
10	Still Water		15.00	t	2025-08-22 10:38:56.234995+02	assets/StillWater.jpg	10	2025-08-22 10:38:56.235005+02	Non-Alcoholic	5	10
6	Manhattan		65.00	f	2025-08-22 10:21:22.402221+02	assets/manhatten_pJnqEBU.png	0	2025-09-18 15:07:41.562387+02	Alcoholic	5	10
4	Switch		15.00	t	2025-08-22 10:05:25.948784+02	assets/switch.jpeg	9	2025-09-18 15:14:19.587892+02	Non-Alcoholic	5	10
3	Tequila		50.00	t	2025-08-20 18:23:48.03699+02	assets/tequila.png	10	2025-09-18 15:14:31.570379+02	Alcoholic	5	10
\.


--
-- Data for Name: barbackend_order; Type: TABLE DATA; Schema: public; Owner: baruser
--

COPY public.barbackend_order (id, status, total_price, created_at, updated_at, user_id, note) FROM stdin;
51	pending	35.00	2025-09-18 22:10:24.899523+02	2025-09-18 22:10:24.899534+02	2	
1	pending	130.00	2025-09-17 10:55:34.748661+02	2025-09-17 10:55:35.030743+02	2	
52	pending	25.00	2025-09-18 22:13:16.929139+02	2025-09-18 22:13:16.92915+02	2	
53	pending	80.00	2025-09-18 22:13:45.771165+02	2025-09-18 22:13:45.771176+02	2	
54	pending	35.00	2025-09-18 22:14:26.095774+02	2025-09-18 22:14:26.095787+02	2	
3	pending	105.00	2025-09-17 11:02:33.226489+02	2025-09-17 11:02:33.368469+02	2	
4	pending	115.00	2025-09-17 11:27:06.429952+02	2025-09-17 11:27:06.571692+02	2	
5	pending	115.00	2025-09-17 11:28:37.483966+02	2025-09-17 11:28:37.618163+02	2	
55	pending	115.00	2025-09-18 23:54:37.341299+02	2025-09-18 23:54:37.822947+02	2	
6	pending	115.00	2025-09-17 11:29:41.655566+02	2025-09-17 11:29:41.726187+02	2	
7	pending	130.00	2025-09-17 11:30:04.899995+02	2025-09-17 11:30:04.957874+02	2	
8	pending	115.00	2025-09-17 11:30:44.470977+02	2025-09-17 11:30:44.60742+02	2	
56	pending	115.00	2025-09-22 16:10:15.752469+02	2025-09-22 16:10:17.206238+02	2	
9	pending	130.00	2025-09-17 11:32:56.189947+02	2025-09-17 11:32:56.33425+02	2	
10	pending	0.00	2025-09-17 11:37:52.543421+02	2025-09-17 11:37:52.543431+02	1	
11	pending	0.00	2025-09-17 11:38:36.539175+02	2025-09-17 11:38:36.539184+02	1	
12	pending	230.00	2025-09-17 11:39:54.100248+02	2025-09-17 11:39:54.857594+02	2	
13	pending	115.00	2025-09-17 11:44:34.545625+02	2025-09-17 11:44:34.739212+02	2	
14	pending	35.00	2025-09-17 21:07:02.326791+02	2025-09-17 21:07:02.326808+02	2	
57	pending	75.00	2025-09-22 16:11:15.530693+02	2025-09-22 16:11:15.868837+02	2	
2	ready	115.00	2025-09-17 11:00:50.406906+02	2025-09-18 14:42:18.080362+02	2	
15	pending	320.00	2025-09-18 21:27:51.279244+02	2025-09-18 21:27:51.279257+02	2	
16	pending	160.00	2025-09-18 21:29:24.764493+02	2025-09-18 21:29:24.764504+02	2	
17	pending	160.00	2025-09-18 21:29:44.196264+02	2025-09-18 21:29:44.196275+02	2	
18	pending	35.00	2025-09-18 21:31:12.884534+02	2025-09-18 21:31:12.884546+02	2	
19	pending	130.00	2025-09-18 21:32:15.666611+02	2025-09-18 21:32:15.7302+02	2	
20	pending	160.00	2025-09-18 21:33:33.63054+02	2025-09-18 21:33:33.630552+02	2	
21	pending	100.00	2025-09-18 21:34:54.642724+02	2025-09-18 21:34:54.642736+02	2	
22	pending	160.00	2025-09-18 21:35:29.666836+02	2025-09-18 21:35:29.666849+02	2	
23	pending	130.00	2025-09-18 21:37:03.537258+02	2025-09-18 21:37:03.598243+02	2	
24	pending	105.00	2025-09-18 21:37:50.16959+02	2025-09-18 21:37:50.169602+02	2	
58	pending	115.00	2025-09-22 16:11:42.876606+02	2025-09-22 16:11:43.257768+02	2	
25	pending	115.00	2025-09-18 21:40:08.841113+02	2025-09-18 21:40:08.906341+02	2	
26	pending	70.00	2025-09-18 21:49:16.239862+02	2025-09-18 21:49:16.239885+02	2	
27	pending	105.00	2025-09-18 21:49:46.554358+02	2025-09-18 21:49:46.706928+02	2	
28	pending	115.00	2025-09-18 21:52:39.445229+02	2025-09-18 21:52:39.592574+02	2	
29	pending	80.00	2025-09-18 21:54:42.000447+02	2025-09-18 21:54:42.000459+02	2	
30	pending	160.00	2025-09-18 21:55:16.260495+02	2025-09-18 21:55:16.260508+02	2	
31	pending	80.00	2025-09-18 21:55:46.570622+02	2025-09-18 21:55:46.570633+02	2	
32	pending	70.00	2025-09-18 21:56:06.950906+02	2025-09-18 21:56:06.950917+02	2	
59	pending	115.00	2025-09-22 16:13:27.242369+02	2025-09-22 16:13:27.305339+02	2	
33	pending	130.00	2025-09-18 21:57:32.021603+02	2025-09-18 21:57:32.331269+02	2	
34	pending	105.00	2025-09-18 21:58:59.814114+02	2025-09-18 21:58:59.874119+02	2	
35	pending	35.00	2025-09-18 21:59:43.702968+02	2025-09-18 21:59:43.70298+02	2	
36	pending	80.00	2025-09-18 22:00:10.853199+02	2025-09-18 22:00:10.85321+02	2	
37	pending	35.00	2025-09-18 22:00:51.9706+02	2025-09-18 22:00:51.970614+02	2	
38	pending	80.00	2025-09-18 22:01:15.021273+02	2025-09-18 22:01:15.021284+02	2	
39	pending	80.00	2025-09-18 22:01:38.058247+02	2025-09-18 22:01:38.058259+02	2	
40	pending	35.00	2025-09-18 22:03:25.815595+02	2025-09-18 22:03:25.815606+02	2	
41	pending	35.00	2025-09-18 22:04:30.192015+02	2025-09-18 22:04:30.192025+02	2	
42	pending	160.00	2025-09-18 22:05:02.240582+02	2025-09-18 22:05:02.240594+02	2	
43	pending	70.00	2025-09-18 22:05:31.631401+02	2025-09-18 22:05:31.631413+02	2	
44	pending	80.00	2025-09-18 22:06:08.471486+02	2025-09-18 22:06:08.471497+02	2	
45	pending	80.00	2025-09-18 22:06:26.084486+02	2025-09-18 22:06:26.084498+02	2	
46	pending	80.00	2025-09-18 22:07:00.182524+02	2025-09-18 22:07:00.182536+02	2	
47	pending	80.00	2025-09-18 22:07:19.377523+02	2025-09-18 22:07:19.377533+02	2	
48	pending	35.00	2025-09-18 22:08:17.932989+02	2025-09-18 22:08:17.933006+02	2	
49	pending	25.00	2025-09-18 22:08:33.338122+02	2025-09-18 22:08:33.338134+02	2	
50	pending	35.00	2025-09-18 22:09:09.179905+02	2025-09-18 22:09:09.179922+02	2	
61	pending	115.00	2025-09-22 18:42:02.949125+02	2025-09-22 18:42:03.914618+02	2	
62	pending	115.00	2025-09-22 18:52:17.734301+02	2025-09-22 18:52:17.966746+02	2	
\.


--
-- Data for Name: barbackend_orderitem; Type: TABLE DATA; Schema: public; Owner: baruser
--

COPY public.barbackend_orderitem (id, quantity, drink_id, order_id) FROM stdin;
1	1	1	1
2	1	8	1
3	1	1	2
4	1	9	2
5	1	1	3
6	1	5	3
7	1	1	4
8	1	9	4
9	1	1	5
10	1	9	5
11	1	1	6
12	1	9	6
13	1	1	7
14	1	2	7
15	1	1	8
16	1	9	8
17	1	1	9
18	1	8	9
19	2	1	12
20	2	9	12
21	1	1	13
22	1	9	13
23	1	9	14
24	4	1	15
25	2	1	16
26	2	1	17
27	1	9	18
28	1	2	19
29	1	1	19
30	2	1	20
31	2	2	21
32	2	1	22
33	1	2	23
34	1	1	23
35	3	9	24
36	1	9	25
37	1	1	25
38	2	9	26
39	1	1	27
40	1	5	27
41	1	1	28
42	1	9	28
43	1	1	29
44	2	1	30
45	1	1	31
46	2	9	32
47	1	1	33
48	1	2	33
49	1	1	34
50	1	5	34
51	1	9	35
52	1	1	36
53	1	9	37
54	1	1	38
55	1	1	39
56	1	9	40
57	1	9	41
58	2	1	42
59	2	9	43
60	1	1	44
61	1	1	45
62	1	1	46
63	1	1	47
64	1	9	48
65	1	5	49
66	1	9	50
67	1	9	51
68	1	5	52
69	1	1	53
70	1	9	54
71	1	1	55
72	1	9	55
73	1	1	56
74	1	9	56
75	1	2	57
76	1	5	57
77	1	1	58
78	1	9	58
79	1	1	59
80	1	9	59
83	1	1	61
84	1	9	61
85	1	1	62
86	1	9	62
\.


--
-- Data for Name: barbackend_orderotp; Type: TABLE DATA; Schema: public; Owner: baruser
--

COPY public.barbackend_orderotp (id, code_hash, code_plain, last_sent_at, is_used, created_at, updated_at, order_id) FROM stdin;
1	pbkdf2_sha256$1000000$KKHT75mVndf0b9287w90c1$rXuP8pXwGe/dSZzAMDU1QTG6JOkwGzcZjBBq/rfZUwM=	893525	2025-09-18 14:42:18.060007+02	f	2025-09-18 14:42:17.646681+02	2025-09-18 14:42:18.060124+02	2
\.


--
-- Data for Name: barbackend_user; Type: TABLE DATA; Schema: public; Owner: baruser
--

COPY public.barbackend_user (id, username, email, role, created_at, date_joined, is_active, is_staff, is_superuser, last_login, password, is_admin) FROM stdin;
1	Samus	samus@foobar.co.za	customer	2025-09-10 13:05:48.385119+02	2025-09-10 13:05:48.385105+02	t	f	f	\N	pbkdf2_sha256$1000000$ZcLMzw1OKClbMGSHr1wfmW$edQtMMxVfuR1/svODlTAYkyHOdfsZqH6H4/TFuvLE4M=	f
2	Faten	fatensaud04@gmail.com	customer	2025-09-10 13:08:49.003282+02	2025-09-10 13:08:49.003274+02	t	f	f	\N	pbkdf2_sha256$1000000$Lxxk4qdIHsSx38HhSTQWUC$A1efroK3tyc2wwQ+07nU18ZonAieG6KTi42rkoQ0LAY=	f
3	Bob	bob@foo.co.za	customer	2025-09-10 13:32:41.742581+02	2025-09-10 13:32:41.742568+02	t	f	f	\N	pbkdf2_sha256$1000000$e2uoCbnpLDDORDG4UjI1aZ$2hrzIt2DQkA3kfi/p3Z9M7ClhOs1HYbGw2B0oEBK/+0=	f
4	default_staff	staff@example.com	staff	2025-09-17 21:05:24.045179+02	2025-09-17 21:05:24.045152+02	t	t	f	\N	pbkdf2_sha256$1000000$gs7eUaTsnboBQcIG3pHNoP$LfGpHXbJPOW+S49iLV1VgBLJJ95CVUMAHLizg+c9ZAg=	f
5	John	john@sun.ac.za	customer	2025-09-18 14:38:08.151137+02	2025-09-18 14:38:08.15112+02	t	f	f	\N	pbkdf2_sha256$1000000$5JomEQtwOopmYw4s7T5tvu$eP9IYYRb6siXRYGV6K8lxoKy6K4Dey6+8Zr2ht3Hllw=	f
\.


--
-- Data for Name: barbackend_user_groups; Type: TABLE DATA; Schema: public; Owner: baruser
--

COPY public.barbackend_user_groups (id, user_id, group_id) FROM stdin;
\.


--
-- Data for Name: barbackend_user_user_permissions; Type: TABLE DATA; Schema: public; Owner: baruser
--

COPY public.barbackend_user_user_permissions (id, user_id, permission_id) FROM stdin;
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: baruser
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: baruser
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	permission
3	auth	group
4	auth	user
5	contenttypes	contenttype
6	sessions	session
7	barbackend	drink
8	barbackend	order
9	barbackend	user
10	barbackend	orderitem
11	barbackend	cart
12	barbackend	cartitem
13	barbackend	orderotp
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: baruser
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2025-08-11 17:40:54.88937+02
2	auth	0001_initial	2025-08-11 17:40:55.678309+02
3	admin	0001_initial	2025-08-11 17:40:56.500005+02
4	admin	0002_logentry_remove_auto_add	2025-08-11 17:40:56.518439+02
5	admin	0003_logentry_add_action_flag_choices	2025-08-11 17:40:56.549361+02
6	contenttypes	0002_remove_content_type_name	2025-08-11 17:40:56.568894+02
7	auth	0002_alter_permission_name_max_length	2025-08-11 17:40:56.586827+02
8	auth	0003_alter_user_email_max_length	2025-08-11 17:40:56.60928+02
9	auth	0004_alter_user_username_opts	2025-08-11 17:40:56.629407+02
10	auth	0005_alter_user_last_login_null	2025-08-11 17:40:56.650026+02
11	auth	0006_require_contenttypes_0002	2025-08-11 17:40:56.665927+02
12	auth	0007_alter_validators_add_error_messages	2025-08-11 17:40:56.682749+02
13	auth	0008_alter_user_username_max_length	2025-08-11 17:40:56.746834+02
14	auth	0009_alter_user_last_name_max_length	2025-08-11 17:40:56.764072+02
15	auth	0010_alter_group_name_max_length	2025-08-11 17:40:56.786003+02
16	auth	0011_update_proxy_permissions	2025-08-11 17:40:56.804609+02
17	auth	0012_alter_user_first_name_max_length	2025-08-11 17:40:56.827781+02
18	barbackend	0001_initial	2025-08-11 17:40:58.363915+02
19	barbackend	0002_alter_order_status	2025-08-11 17:40:58.378159+02
20	sessions	0001_initial	2025-08-11 17:40:58.61434+02
21	barbackend	0003_drink_image	2025-08-18 15:25:17.100592+02
22	barbackend	0003_cart_note	2025-08-18 15:56:31.552807+02
23	barbackend	0004_order_note	2025-08-18 15:56:31.596092+02
24	barbackend	0005_merge_0003_drink_image_0004_order_note	2025-08-18 15:56:31.621633+02
25	barbackend	0006_remove_cart_note_remove_order_note	2025-08-18 20:52:07.101557+02
26	barbackend	0006_remove_cart_note_remove_order_note_drink_stock_and_more	2025-08-19 08:22:36.724856+02
27	barbackend	0007_drink_category	2025-08-19 08:22:36.796749+02
28	barbackend	0008_alter_drink_image	2025-08-19 18:10:48.524514+02
29	barbackend	0009_alter_drink_image	2025-08-19 21:15:11.572499+02
30	barbackend	0008_cart_note_order_note	2025-08-20 08:38:06.75994+02
31	barbackend	0009_merge_20250819_1942	2025-08-20 09:22:20.81962+02
32	barbackend	0010_alter_drink_image	2025-08-20 09:22:20.84228+02
33	barbackend	0011_alter_drink_image	2025-08-22 09:44:14.305754+02
34	barbackend	0012_orderotp	2025-09-07 21:51:40.628501+02
35	barbackend	0013_remove_orderotp_attempts_remove_orderotp_expires_at_and_more	2025-09-07 21:51:41.368599+02
36	barbackend	0014_uniq_active_otp_code_plain	2025-09-07 21:51:41.381686+02
37	barbackend	0009_merge_20250822_2043	2025-09-07 21:51:41.393871+02
38	barbackend	0015_merge_20250903_1347	2025-09-07 21:51:41.406916+02
39	barbackend	0016_alter_user_managers_remove_user_password_hash_and_more	2025-09-07 21:51:41.41926+02
40	barbackend	0017_drink_low_stock_threshold	2025-09-07 21:51:41.432251+02
43	barbackend	0018_user_is_admin	2025-09-07 22:01:09.07235+02
44	barbackend	0019_rename_low_stock_threshold_add_low_stock_threshold	2025-09-11 21:29:05.161293+02
45	barbackend	0020_alter_drink_unavailable_threshold	2025-09-11 21:29:05.200858+02
46	barbackend	0021_cart_updated_at	2025-09-22 22:48:09.233693+02
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: baruser
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
\.


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: baruser
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: baruser
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: baruser
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 84, true);


--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: baruser
--

SELECT pg_catalog.setval('public.auth_user_groups_id_seq', 1, false);


--
-- Name: auth_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: baruser
--

SELECT pg_catalog.setval('public.auth_user_id_seq', 1, false);


--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: baruser
--

SELECT pg_catalog.setval('public.auth_user_user_permissions_id_seq', 1, false);


--
-- Name: barbackend_cart_id_seq; Type: SEQUENCE SET; Schema: public; Owner: baruser
--

SELECT pg_catalog.setval('public.barbackend_cart_id_seq', 10, true);


--
-- Name: barbackend_cartitem_id_seq; Type: SEQUENCE SET; Schema: public; Owner: baruser
--

SELECT pg_catalog.setval('public.barbackend_cartitem_id_seq', 174, true);


--
-- Name: barbackend_drink_id_seq; Type: SEQUENCE SET; Schema: public; Owner: baruser
--

SELECT pg_catalog.setval('public.barbackend_drink_id_seq', 10, true);


--
-- Name: barbackend_order_id_seq; Type: SEQUENCE SET; Schema: public; Owner: baruser
--

SELECT pg_catalog.setval('public.barbackend_order_id_seq', 62, true);


--
-- Name: barbackend_orderitem_id_seq; Type: SEQUENCE SET; Schema: public; Owner: baruser
--

SELECT pg_catalog.setval('public.barbackend_orderitem_id_seq', 86, true);


--
-- Name: barbackend_orderotp_id_seq; Type: SEQUENCE SET; Schema: public; Owner: baruser
--

SELECT pg_catalog.setval('public.barbackend_orderotp_id_seq', 1, true);


--
-- Name: barbackend_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: baruser
--

SELECT pg_catalog.setval('public.barbackend_user_groups_id_seq', 1, false);


--
-- Name: barbackend_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: baruser
--

SELECT pg_catalog.setval('public.barbackend_user_id_seq', 5, true);


--
-- Name: barbackend_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: baruser
--

SELECT pg_catalog.setval('public.barbackend_user_user_permissions_id_seq', 1, false);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: baruser
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 1, false);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: baruser
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 13, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: baruser
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 46, true);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: baruser
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: baruser
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: baruser
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: baruser
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: baruser
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: baruser
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: baruser
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_user_id_group_id_94350c0c_uniq; Type: CONSTRAINT; Schema: public; Owner: baruser
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id);


--
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: public; Owner: baruser
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: baruser
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_permission_id_14a6b632_uniq; Type: CONSTRAINT; Schema: public; Owner: baruser
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id);


--
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: public; Owner: baruser
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- Name: barbackend_cart barbackend_cart_pkey; Type: CONSTRAINT; Schema: public; Owner: baruser
--

ALTER TABLE ONLY public.barbackend_cart
    ADD CONSTRAINT barbackend_cart_pkey PRIMARY KEY (id);


--
-- Name: barbackend_cart barbackend_cart_user_id_key; Type: CONSTRAINT; Schema: public; Owner: baruser
--

ALTER TABLE ONLY public.barbackend_cart
    ADD CONSTRAINT barbackend_cart_user_id_key UNIQUE (user_id);


--
-- Name: barbackend_cartitem barbackend_cartitem_cart_id_drink_id_5b25342a_uniq; Type: CONSTRAINT; Schema: public; Owner: baruser
--

ALTER TABLE ONLY public.barbackend_cartitem
    ADD CONSTRAINT barbackend_cartitem_cart_id_drink_id_5b25342a_uniq UNIQUE (cart_id, drink_id);


--
-- Name: barbackend_cartitem barbackend_cartitem_pkey; Type: CONSTRAINT; Schema: public; Owner: baruser
--

ALTER TABLE ONLY public.barbackend_cartitem
    ADD CONSTRAINT barbackend_cartitem_pkey PRIMARY KEY (id);


--
-- Name: barbackend_drink barbackend_drink_pkey; Type: CONSTRAINT; Schema: public; Owner: baruser
--

ALTER TABLE ONLY public.barbackend_drink
    ADD CONSTRAINT barbackend_drink_pkey PRIMARY KEY (id);


--
-- Name: barbackend_order barbackend_order_pkey; Type: CONSTRAINT; Schema: public; Owner: baruser
--

ALTER TABLE ONLY public.barbackend_order
    ADD CONSTRAINT barbackend_order_pkey PRIMARY KEY (id);


--
-- Name: barbackend_orderitem barbackend_orderitem_pkey; Type: CONSTRAINT; Schema: public; Owner: baruser
--

ALTER TABLE ONLY public.barbackend_orderitem
    ADD CONSTRAINT barbackend_orderitem_pkey PRIMARY KEY (id);


--
-- Name: barbackend_orderotp barbackend_orderotp_order_id_key; Type: CONSTRAINT; Schema: public; Owner: baruser
--

ALTER TABLE ONLY public.barbackend_orderotp
    ADD CONSTRAINT barbackend_orderotp_order_id_key UNIQUE (order_id);


--
-- Name: barbackend_orderotp barbackend_orderotp_pkey; Type: CONSTRAINT; Schema: public; Owner: baruser
--

ALTER TABLE ONLY public.barbackend_orderotp
    ADD CONSTRAINT barbackend_orderotp_pkey PRIMARY KEY (id);


--
-- Name: barbackend_user barbackend_user_email_key; Type: CONSTRAINT; Schema: public; Owner: baruser
--

ALTER TABLE ONLY public.barbackend_user
    ADD CONSTRAINT barbackend_user_email_key UNIQUE (email);


--
-- Name: barbackend_user_groups barbackend_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: baruser
--

ALTER TABLE ONLY public.barbackend_user_groups
    ADD CONSTRAINT barbackend_user_groups_pkey PRIMARY KEY (id);


--
-- Name: barbackend_user_groups barbackend_user_groups_user_id_group_id_302d3e94_uniq; Type: CONSTRAINT; Schema: public; Owner: baruser
--

ALTER TABLE ONLY public.barbackend_user_groups
    ADD CONSTRAINT barbackend_user_groups_user_id_group_id_302d3e94_uniq UNIQUE (user_id, group_id);


--
-- Name: barbackend_user barbackend_user_pkey; Type: CONSTRAINT; Schema: public; Owner: baruser
--

ALTER TABLE ONLY public.barbackend_user
    ADD CONSTRAINT barbackend_user_pkey PRIMARY KEY (id);


--
-- Name: barbackend_user_user_permissions barbackend_user_user_per_user_id_permission_id_e070f34a_uniq; Type: CONSTRAINT; Schema: public; Owner: baruser
--

ALTER TABLE ONLY public.barbackend_user_user_permissions
    ADD CONSTRAINT barbackend_user_user_per_user_id_permission_id_e070f34a_uniq UNIQUE (user_id, permission_id);


--
-- Name: barbackend_user_user_permissions barbackend_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: baruser
--

ALTER TABLE ONLY public.barbackend_user_user_permissions
    ADD CONSTRAINT barbackend_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: barbackend_user barbackend_user_username_key; Type: CONSTRAINT; Schema: public; Owner: baruser
--

ALTER TABLE ONLY public.barbackend_user
    ADD CONSTRAINT barbackend_user_username_key UNIQUE (username);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: baruser
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: baruser
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: baruser
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: baruser
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: baruser
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: baruser
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: baruser
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: baruser
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: baruser
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: auth_user_groups_group_id_97559544; Type: INDEX; Schema: public; Owner: baruser
--

CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);


--
-- Name: auth_user_groups_user_id_6a12ed8b; Type: INDEX; Schema: public; Owner: baruser
--

CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);


--
-- Name: auth_user_user_permissions_permission_id_1fbb5f2c; Type: INDEX; Schema: public; Owner: baruser
--

CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);


--
-- Name: auth_user_user_permissions_user_id_a95ead1b; Type: INDEX; Schema: public; Owner: baruser
--

CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);


--
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: public; Owner: baruser
--

CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);


--
-- Name: barbackend_cartitem_cart_id_1981aa35; Type: INDEX; Schema: public; Owner: baruser
--

CREATE INDEX barbackend_cartitem_cart_id_1981aa35 ON public.barbackend_cartitem USING btree (cart_id);


--
-- Name: barbackend_cartitem_drink_id_45acf3f2; Type: INDEX; Schema: public; Owner: baruser
--

CREATE INDEX barbackend_cartitem_drink_id_45acf3f2 ON public.barbackend_cartitem USING btree (drink_id);


--
-- Name: barbackend_order_user_id_4bc7d8b6; Type: INDEX; Schema: public; Owner: baruser
--

CREATE INDEX barbackend_order_user_id_4bc7d8b6 ON public.barbackend_order USING btree (user_id);


--
-- Name: barbackend_orderitem_drink_id_3130a7e7; Type: INDEX; Schema: public; Owner: baruser
--

CREATE INDEX barbackend_orderitem_drink_id_3130a7e7 ON public.barbackend_orderitem USING btree (drink_id);


--
-- Name: barbackend_orderitem_order_id_f9735e29; Type: INDEX; Schema: public; Owner: baruser
--

CREATE INDEX barbackend_orderitem_order_id_f9735e29 ON public.barbackend_orderitem USING btree (order_id);


--
-- Name: barbackend_user_email_759a19ed_like; Type: INDEX; Schema: public; Owner: baruser
--

CREATE INDEX barbackend_user_email_759a19ed_like ON public.barbackend_user USING btree (email varchar_pattern_ops);


--
-- Name: barbackend_user_groups_group_id_6de77435; Type: INDEX; Schema: public; Owner: baruser
--

CREATE INDEX barbackend_user_groups_group_id_6de77435 ON public.barbackend_user_groups USING btree (group_id);


--
-- Name: barbackend_user_groups_user_id_874defee; Type: INDEX; Schema: public; Owner: baruser
--

CREATE INDEX barbackend_user_groups_user_id_874defee ON public.barbackend_user_groups USING btree (user_id);


--
-- Name: barbackend_user_user_permissions_permission_id_052a236b; Type: INDEX; Schema: public; Owner: baruser
--

CREATE INDEX barbackend_user_user_permissions_permission_id_052a236b ON public.barbackend_user_user_permissions USING btree (permission_id);


--
-- Name: barbackend_user_user_permissions_user_id_3dff7233; Type: INDEX; Schema: public; Owner: baruser
--

CREATE INDEX barbackend_user_user_permissions_user_id_3dff7233 ON public.barbackend_user_user_permissions USING btree (user_id);


--
-- Name: barbackend_user_username_33deff3a_like; Type: INDEX; Schema: public; Owner: baruser
--

CREATE INDEX barbackend_user_username_33deff3a_like ON public.barbackend_user USING btree (username varchar_pattern_ops);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: baruser
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: baruser
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: baruser
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: baruser
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: uniq_active_otp_code_plain; Type: INDEX; Schema: public; Owner: baruser
--

CREATE UNIQUE INDEX uniq_active_otp_code_plain ON public.barbackend_orderotp USING btree (code_plain) WHERE (NOT is_used);


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: baruser
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: baruser
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: baruser
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_group_id_97559544_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: baruser
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_user_id_6a12ed8b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: baruser
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: baruser
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: baruser
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: barbackend_cart barbackend_cart_user_id_ad62b38c_fk_barbackend_user_id; Type: FK CONSTRAINT; Schema: public; Owner: baruser
--

ALTER TABLE ONLY public.barbackend_cart
    ADD CONSTRAINT barbackend_cart_user_id_ad62b38c_fk_barbackend_user_id FOREIGN KEY (user_id) REFERENCES public.barbackend_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: barbackend_cartitem barbackend_cartitem_cart_id_1981aa35_fk_barbackend_cart_id; Type: FK CONSTRAINT; Schema: public; Owner: baruser
--

ALTER TABLE ONLY public.barbackend_cartitem
    ADD CONSTRAINT barbackend_cartitem_cart_id_1981aa35_fk_barbackend_cart_id FOREIGN KEY (cart_id) REFERENCES public.barbackend_cart(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: barbackend_cartitem barbackend_cartitem_drink_id_45acf3f2_fk_barbackend_drink_id; Type: FK CONSTRAINT; Schema: public; Owner: baruser
--

ALTER TABLE ONLY public.barbackend_cartitem
    ADD CONSTRAINT barbackend_cartitem_drink_id_45acf3f2_fk_barbackend_drink_id FOREIGN KEY (drink_id) REFERENCES public.barbackend_drink(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: barbackend_orderitem barbackend_orderitem_drink_id_3130a7e7_fk_barbackend_drink_id; Type: FK CONSTRAINT; Schema: public; Owner: baruser
--

ALTER TABLE ONLY public.barbackend_orderitem
    ADD CONSTRAINT barbackend_orderitem_drink_id_3130a7e7_fk_barbackend_drink_id FOREIGN KEY (drink_id) REFERENCES public.barbackend_drink(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: barbackend_orderitem barbackend_orderitem_order_id_f9735e29_fk_barbackend_order_id; Type: FK CONSTRAINT; Schema: public; Owner: baruser
--

ALTER TABLE ONLY public.barbackend_orderitem
    ADD CONSTRAINT barbackend_orderitem_order_id_f9735e29_fk_barbackend_order_id FOREIGN KEY (order_id) REFERENCES public.barbackend_order(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: barbackend_orderotp barbackend_orderotp_order_id_85a19be7_fk_barbackend_order_id; Type: FK CONSTRAINT; Schema: public; Owner: baruser
--

ALTER TABLE ONLY public.barbackend_orderotp
    ADD CONSTRAINT barbackend_orderotp_order_id_85a19be7_fk_barbackend_order_id FOREIGN KEY (order_id) REFERENCES public.barbackend_order(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: barbackend_user_groups barbackend_user_groups_group_id_6de77435_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: baruser
--

ALTER TABLE ONLY public.barbackend_user_groups
    ADD CONSTRAINT barbackend_user_groups_group_id_6de77435_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: barbackend_user_groups barbackend_user_groups_user_id_874defee_fk_barbackend_user_id; Type: FK CONSTRAINT; Schema: public; Owner: baruser
--

ALTER TABLE ONLY public.barbackend_user_groups
    ADD CONSTRAINT barbackend_user_groups_user_id_874defee_fk_barbackend_user_id FOREIGN KEY (user_id) REFERENCES public.barbackend_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: barbackend_user_user_permissions barbackend_user_user_permission_id_052a236b_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: baruser
--

ALTER TABLE ONLY public.barbackend_user_user_permissions
    ADD CONSTRAINT barbackend_user_user_permission_id_052a236b_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: barbackend_user_user_permissions barbackend_user_user_user_id_3dff7233_fk_barbacken; Type: FK CONSTRAINT; Schema: public; Owner: baruser
--

ALTER TABLE ONLY public.barbackend_user_user_permissions
    ADD CONSTRAINT barbackend_user_user_user_id_3dff7233_fk_barbacken FOREIGN KEY (user_id) REFERENCES public.barbackend_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: baruser
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: baruser
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: SCHEMA public; Type: ACL; Schema: -; Owner: baruser
--

REVOKE USAGE ON SCHEMA public FROM PUBLIC;
GRANT ALL ON SCHEMA public TO PUBLIC;


--
-- PostgreSQL database dump complete
--

\unrestrict 4C9dSDZ1yyiYKgc9Sqbv042bIggXT7TuOIuhN0Trb4GTHm4isYkTUXUdns5VZ8p

