--
-- PostgreSQL database dump
--

-- Dumped from database version 14.18 (Debian 14.18-1.pgdg120+1)
-- Dumped by pg_dump version 14.18 (Ubuntu 14.18-0ubuntu0.22.04.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: baruser
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO baruser;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: baruser
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: baruser
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO baruser;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: baruser
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: baruser
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO baruser;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: baruser
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user; Type: TABLE; Schema: public; Owner: baruser
--

CREATE TABLE public.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


ALTER TABLE public.auth_user OWNER TO baruser;

--
-- Name: auth_user_groups; Type: TABLE; Schema: public; Owner: baruser
--

CREATE TABLE public.auth_user_groups (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.auth_user_groups OWNER TO baruser;

--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: baruser
--

ALTER TABLE public.auth_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: public; Owner: baruser
--

ALTER TABLE public.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_user_permissions; Type: TABLE; Schema: public; Owner: baruser
--

CREATE TABLE public.auth_user_user_permissions (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_user_user_permissions OWNER TO baruser;

--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: baruser
--

ALTER TABLE public.auth_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: barbackend_cart; Type: TABLE; Schema: public; Owner: baruser
--

CREATE TABLE public.barbackend_cart (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    user_id bigint NOT NULL,
    note text NOT NULL
);


ALTER TABLE public.barbackend_cart OWNER TO baruser;

--
-- Name: barbackend_cart_id_seq; Type: SEQUENCE; Schema: public; Owner: baruser
--

ALTER TABLE public.barbackend_cart ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.barbackend_cart_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: barbackend_cartitem; Type: TABLE; Schema: public; Owner: baruser
--

CREATE TABLE public.barbackend_cartitem (
    id bigint NOT NULL,
    quantity integer NOT NULL,
    added_at timestamp with time zone NOT NULL,
    cart_id bigint NOT NULL,
    drink_id bigint NOT NULL,
    CONSTRAINT barbackend_cartitem_quantity_check CHECK ((quantity >= 0))
);


ALTER TABLE public.barbackend_cartitem OWNER TO baruser;

--
-- Name: barbackend_cartitem_id_seq; Type: SEQUENCE; Schema: public; Owner: baruser
--

ALTER TABLE public.barbackend_cartitem ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.barbackend_cartitem_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: barbackend_drink; Type: TABLE; Schema: public; Owner: baruser
--

CREATE TABLE public.barbackend_drink (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    description text NOT NULL,
    price numeric(6,2) NOT NULL,
    available boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    image character varying(100) NOT NULL,
    stock integer NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    category character varying(50) NOT NULL,
    CONSTRAINT barbackend_drink_stock_check CHECK ((stock >= 0))
);


ALTER TABLE public.barbackend_drink OWNER TO baruser;

--
-- Name: barbackend_drink_id_seq; Type: SEQUENCE; Schema: public; Owner: baruser
--

ALTER TABLE public.barbackend_drink ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.barbackend_drink_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: barbackend_order; Type: TABLE; Schema: public; Owner: baruser
--

CREATE TABLE public.barbackend_order (
    id bigint NOT NULL,
    status character varying(30) NOT NULL,
    total_price numeric(8,2) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    user_id bigint NOT NULL,
    note text NOT NULL
);


ALTER TABLE public.barbackend_order OWNER TO baruser;

--
-- Name: barbackend_order_id_seq; Type: SEQUENCE; Schema: public; Owner: baruser
--

ALTER TABLE public.barbackend_order ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.barbackend_order_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: barbackend_orderitem; Type: TABLE; Schema: public; Owner: baruser
--

CREATE TABLE public.barbackend_orderitem (
    id bigint NOT NULL,
    quantity integer NOT NULL,
    drink_id bigint NOT NULL,
    order_id bigint NOT NULL,
    CONSTRAINT barbackend_orderitem_quantity_check CHECK ((quantity >= 0))
);


ALTER TABLE public.barbackend_orderitem OWNER TO baruser;

--
-- Name: barbackend_orderitem_id_seq; Type: SEQUENCE; Schema: public; Owner: baruser
--

ALTER TABLE public.barbackend_orderitem ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.barbackend_orderitem_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: barbackend_user; Type: TABLE; Schema: public; Owner: baruser
--

CREATE TABLE public.barbackend_user (
    id bigint NOT NULL,
    username character varying(50) NOT NULL,
    email character varying(254) NOT NULL,
    password_hash character varying(255) NOT NULL,
    role character varying(20) NOT NULL,
    created_at timestamp with time zone NOT NULL
);


ALTER TABLE public.barbackend_user OWNER TO baruser;

--
-- Name: barbackend_user_id_seq; Type: SEQUENCE; Schema: public; Owner: baruser
--

ALTER TABLE public.barbackend_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.barbackend_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: baruser
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO baruser;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: baruser
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: baruser
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO baruser;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: baruser
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: baruser
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO baruser;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: baruser
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: baruser
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO baruser;

--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: baruser
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: baruser
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: baruser
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	2	add_permission
6	Can change permission	2	change_permission
7	Can delete permission	2	delete_permission
8	Can view permission	2	view_permission
9	Can add group	3	add_group
10	Can change group	3	change_group
11	Can delete group	3	delete_group
12	Can view group	3	view_group
13	Can add user	4	add_user
14	Can change user	4	change_user
15	Can delete user	4	delete_user
16	Can view user	4	view_user
17	Can add content type	5	add_contenttype
18	Can change content type	5	change_contenttype
19	Can delete content type	5	delete_contenttype
20	Can view content type	5	view_contenttype
21	Can add session	6	add_session
22	Can change session	6	change_session
23	Can delete session	6	delete_session
24	Can view session	6	view_session
25	Can add drink	7	add_drink
26	Can change drink	7	change_drink
27	Can delete drink	7	delete_drink
28	Can view drink	7	view_drink
29	Can add order	8	add_order
30	Can change order	8	change_order
31	Can delete order	8	delete_order
32	Can view order	8	view_order
33	Can add user	9	add_user
34	Can change user	9	change_user
35	Can delete user	9	delete_user
36	Can view user	9	view_user
37	Can add order item	10	add_orderitem
38	Can change order item	10	change_orderitem
39	Can delete order item	10	delete_orderitem
40	Can view order item	10	view_orderitem
41	Can add cart	11	add_cart
42	Can change cart	11	change_cart
43	Can delete cart	11	delete_cart
44	Can view cart	11	view_cart
45	Can add cart item	12	add_cartitem
46	Can change cart item	12	change_cartitem
47	Can delete cart item	12	delete_cartitem
48	Can view cart item	12	view_cartitem
\.


--
-- Data for Name: auth_user; Type: TABLE DATA; Schema: public; Owner: baruser
--

COPY public.auth_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined) FROM stdin;
\.


--
-- Data for Name: auth_user_groups; Type: TABLE DATA; Schema: public; Owner: baruser
--

COPY public.auth_user_groups (id, user_id, group_id) FROM stdin;
\.


--
-- Data for Name: auth_user_user_permissions; Type: TABLE DATA; Schema: public; Owner: baruser
--

COPY public.auth_user_user_permissions (id, user_id, permission_id) FROM stdin;
\.


--
-- Data for Name: barbackend_cart; Type: TABLE DATA; Schema: public; Owner: baruser
--

COPY public.barbackend_cart (id, created_at, user_id, note) FROM stdin;
\.


--
-- Data for Name: barbackend_cartitem; Type: TABLE DATA; Schema: public; Owner: baruser
--

COPY public.barbackend_cartitem (id, quantity, added_at, cart_id, drink_id) FROM stdin;
\.


--
-- Data for Name: barbackend_drink; Type: TABLE DATA; Schema: public; Owner: baruser
--

COPY public.barbackend_drink (id, name, description, price, available, created_at, image, stock, updated_at, category) FROM stdin;
1	Espresso Martini		80.00	t	2025-08-20 16:18:56.409879+00	assets/cocktail.png	10	2025-08-20 16:18:56.409904+00	Alcoholic
2	Irish Ale		50.00	t	2025-08-20 16:21:51.568935+00	assets/irishale.png	10	2025-08-20 16:21:51.568951+00	Alcoholic
3	Tequila		50.00	t	2025-08-20 16:23:48.03699+00	assets/tequila.png	10	2025-08-20 16:23:48.037003+00	Alcoholic
4	Switch		15.00	t	2025-08-22 08:05:25.948784+00	assets/switch.jpeg	9	2025-08-22 08:05:25.948797+00	Non-Alcoholic
5	Passion Fruit Lemonade		25.00	t	2025-08-22 08:18:05.001091+00	assets/passionfruit.jpg	15	2025-08-22 08:18:05.001103+00	Non-Alcoholic
6	Manhattan		65.00	f	2025-08-22 08:21:22.402221+00	assets/manhatten_pJnqEBU.png	0	2025-08-22 08:21:22.402231+00	Alcoholic
7	Peach Vodka		60.00	t	2025-08-22 08:23:35.900439+00	assets/peachvodka.jpg	10	2025-08-22 08:23:35.900448+00	Alcoholic
8	Passionfruit Martini		50.00	t	2025-08-22 08:25:42.814953+00	assets/passionmartini.png	10	2025-08-22 08:25:42.814962+00	Alcoholic
9	Gin & Tonic		35.00	t	2025-08-22 08:32:56.958632+00	assets/gintonic.jpg	8	2025-08-22 08:32:56.958643+00	Alcoholic
10	Still Water		15.00	t	2025-08-22 08:38:56.234995+00	assets/StillWater.jpg	10	2025-08-22 08:38:56.235005+00	Non-Alcoholic
\.


--
-- Data for Name: barbackend_order; Type: TABLE DATA; Schema: public; Owner: baruser
--

COPY public.barbackend_order (id, status, total_price, created_at, updated_at, user_id, note) FROM stdin;
1	pending	130.00	2025-08-18 18:33:04.089128+00	2025-08-18 18:33:04.089128+00	1	
2	preparing	160.00	2025-08-19 18:51:03.363423+00	2025-08-19 18:51:03.363423+00	1	
3	cancelled	105.00	2025-08-19 18:51:27.053493+00	2025-08-19 18:51:27.053493+00	1	
4	ready	170.00	2025-08-19 18:51:42.400456+00	2025-08-19 18:51:42.400456+00	1	
5	ready	90.00	2025-08-19 18:51:51.379722+00	2025-08-19 18:51:51.379722+00	1	
6	completed	115.00	2025-08-19 18:52:04.666904+00	2025-08-19 18:52:04.666904+00	1	
7	completed	205.00	2025-08-19 18:52:26.976006+00	2025-08-19 18:52:26.976006+00	1	
\.


--
-- Data for Name: barbackend_orderitem; Type: TABLE DATA; Schema: public; Owner: baruser
--

COPY public.barbackend_orderitem (id, quantity, drink_id, order_id) FROM stdin;
1	2	1	1
2	1	7	1
3	1	2	2
4	2	8	2
5	2	4	2
6	3	9	3
7	1	1	4
8	2	5	4
9	2	7	4
10	2	10	5
11	3	4	5
12	1	9	6
13	2	1	6
14	1	3	7
15	3	8	7
16	2	2	7
\.


--
-- Data for Name: barbackend_user; Type: TABLE DATA; Schema: public; Owner: baruser
--

COPY public.barbackend_user (id, username, email, password_hash, role, created_at) FROM stdin;
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: baruser
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: baruser
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: baruser
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: baruser
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
\.


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: baruser
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: baruser
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: baruser
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 1, false);


--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: baruser
--

SELECT pg_catalog.setval('public.auth_user_groups_id_seq', 1, false);


--
-- Name: auth_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: baruser
--

SELECT pg_catalog.setval('public.auth_user_id_seq', 1, false);


--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: baruser
--

SELECT pg_catalog.setval('public.auth_user_user_permissions_id_seq', 1, false);


--
-- Name: barbackend_cart_id_seq; Type: SEQUENCE SET; Schema: public; Owner: baruser
--

SELECT pg_catalog.setval('public.barbackend_cart_id_seq', 1, false);


--
-- Name: barbackend_cartitem_id_seq; Type: SEQUENCE SET; Schema: public; Owner: baruser
--

SELECT pg_catalog.setval('public.barbackend_cartitem_id_seq', 1, false);


--
-- Name: barbackend_drink_id_seq; Type: SEQUENCE SET; Schema: public; Owner: baruser
--

SELECT pg_catalog.setval('public.barbackend_drink_id_seq', 1, false);


--
-- Name: barbackend_order_id_seq; Type: SEQUENCE SET; Schema: public; Owner: baruser
--

SELECT pg_catalog.setval('public.barbackend_order_id_seq', 1, false);


--
-- Name: barbackend_orderitem_id_seq; Type: SEQUENCE SET; Schema: public; Owner: baruser
--

SELECT pg_catalog.setval('public.barbackend_orderitem_id_seq', 1, false);


--
-- Name: barbackend_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: baruser
--

SELECT pg_catalog.setval('public.barbackend_user_id_seq', 1, false);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: baruser
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 1, false);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: baruser
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 1, false);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: baruser
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 1, false);


--
-- PostgreSQL database dump complete
--

