# Generated by Django 5.2.5 on 2025-08-18 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbackend', '0002_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='drink',
            name='image',
            field=models.TextField(blank=True),
        ),
    ]
