# Generated by Django 5.2.5 on 2025-08-11 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbackend', '0002_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='note',
            field=models.TextField(blank=True, default=''),
        ),
    ]
