# Generated by Django 5.2.5 on 2025-08-18 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barbackend', '0003_drink_image'),
        ('barbackend', '0004_order_note'),
    ]

    operations = [
    ]
