# Generated by Django 5.2.5 on 2025-08-18 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbackend', '0005_merge_0003_drink_image_0004_order_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='note',
        ),
        migrations.RemoveField(
            model_name='order',
            name='note',
        ),
        migrations.AddField(
            model_name='drink',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='drink',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
