# Generated by Django 5.2.5 on 2025-08-18 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbackend', '0006_remove_cart_note_remove_order_note_drink_stock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drink',
            name='category',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
