# Generated by Django 5.2.5 on 2025-08-19 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbackend', '0007_drink_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='image',
            field=models.ImageField(upload_to='assets/'),
        ),
    ]
