# Generated by Django 5.2.5 on 2025-08-19 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbackend', '0007_drink_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='order',
            name='note',
            field=models.TextField(blank=True, default=''),
        ),
    ]
