# Generated by Django 5.2.5 on 2025-08-19 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barbackend', '0008_alter_drink_image'),
        ('barbackend', '0008_cart_note_order_note'),
    ]

    operations = [
    ]
