# Generated by Django 5.2.5 on 2025-08-19 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbackend', '0009_merge_20250819_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='image',
            field=models.ImageField(upload_to='media/assets/'),
        ),
    ]
