# Generated by Django 5.2.5 on 2025-08-20 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbackend', '0010_alter_drink_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='image',
            field=models.ImageField(upload_to='assets/'),
        ),
    ]
