# Generated by Django 5.2.5 on 2025-09-01 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barbackend', '0012_orderotp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderotp',
            name='attempts',
        ),
        migrations.RemoveField(
            model_name='orderotp',
            name='expires_at',
        ),
        migrations.RemoveField(
            model_name='orderotp',
            name='max_attempts',
        ),
    ]
