# Generated by Django 5.2.5 on 2025-09-02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbackend', '0013_remove_orderotp_attempts_remove_orderotp_expires_at_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='orderotp',
            constraint=models.UniqueConstraint(
                fields=('code_plain',),
                condition=models.Q(('is_used', False)),
                name='uniq_active_otp_code_plain',
            ),
        ),
    ]
