# Generated by Django 5.2.5 on 2025-09-03 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barbackend', '0009_merge_20250822_2043'),
        ('barbackend', '0014_uniq_active_otp_code_plain'),
    ]

    operations = [
    ]
