# Generated by Django 5.2.5 on 2025-09-04 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbackend', '0016_alter_user_managers_remove_user_password_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drink',
            name='low_stock_threshold',
            field=models.PositiveIntegerField(default=5, help_text='Below this stock, the drink is unavailable.'),
        ),
    ]
