# Generated by Django 5.2.5 on 2025-09-10 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbackend', '0019_rename_low_stock_threshold_add_low_stock_threshold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='unavailable_threshold',
            field=models.PositiveIntegerField(default=5, help_text='Below this stock, the drink is automatically unavailable.'),
        ),
    ]
