# Generated by Django 5.2.5 on 2025-10-01 16:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbackend', '0022_order_inventory_deducted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('order_received', 'Order Received'), ('preparing_order', 'Preparing Order'), ('ready_for_pickup', 'Ready for Pickup'), ('order_cancelled', 'Order Cancelled'), ('order_delayed', 'Order Delayed'), ('new_order', 'New Order'), ('cancel_request', 'Cancel Request')], max_length=30)),
                ('content', models.TextField(blank=True, help_text='Optional custom message text')),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='barbackend.order')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
