# Generated by Django 5.2.5 on 2025-10-01 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barbackend', '0023_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='is_read',
        ),
    ]
