# Generated by Django 5.2.5 on 2025-10-04 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barbackend', '0024_remove_message_is_read'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
