# Generated by Django 5.2.5 on 2025-10-04 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barbackend', '0026_add_performance_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='cart',
            name='cart_updated_idx',
        ),
        migrations.RemoveIndex(
            model_name='cartitem',
            name='cartitem_cart_drink_idx',
        ),
        migrations.RemoveIndex(
            model_name='drink',
            name='drink_avail_cat_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='order_status_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='order_user_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='order_updated_idx',
        ),
        migrations.RemoveIndex(
            model_name='orderitem',
            name='orderitem_order_drink_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='user_role_active_idx',
        ),
    ]
