# Generated by Django 5.2.5 on 2025-10-06 21:27

import barbackend.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbackend', '0027_remove_cart_cart_updated_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=barbackend.storage_backends.SupabaseStorage, upload_to='assets/'),
        ),
    ]
